version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: 'increase'
  - package-ecosystem: 'docker'
    directory: '/apps/client'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/apps/admin'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/apps/api'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
