version: '3'

services:
  admin:
    container_name: athlonix-admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3100:3100

  client:
    container_name: athlonix-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3102:3102

  api:
    container_name: athlonix-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3103:3103
