services:
  admin:
    container_name: athlonix-admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${ADMIN_PORT}:3100

  client:
    container_name: athlonix-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:3102

  api:
    container_name: athlonix-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: prod
    tty: true
    stdin_open: true
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${API_PORT}:3101
