version: "3"

services:
  admin:
    container_name: athlonix-admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${ADMIN_PORT}:3100
    volumes:
      - /app/node_modules
      - /app/apps/admin/node_modules
      - ./apps/admin:/app/apps/admin

  client:
    container_name: athlonix-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:3102
    volumes:
      - /app/node_modules
      - /app/apps/client/node_modules
      - ./apps/client:/app/apps/client

  api:
    container_name: athlonix-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: dev
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - ${API_PORT}:3101
    volumes:
      - /app/node_modules
      - /app/apps/api/node_modules
      - ./apps/api:/app/apps/api
