
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "isn" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."days" AS ENUM (
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday'
);

ALTER TYPE "public"."days" OWNER TO "postgres";

CREATE TYPE "public"."reaction" AS ENUM (
    'like'
);

ALTER TYPE "public"."reaction" OWNER TO "postgres";

CREATE TYPE "public"."recurrence" AS ENUM (
    'weekly',
    'monthly',
    'annual'
);

ALTER TYPE "public"."recurrence" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES" (
    "id" bigint NOT NULL,
    "max_participants" integer NOT NULL,
    "name" "text" NOT NULL,
    "id_sport" bigint,
    "id_address" bigint,
    "days" "public"."days"[],
    "end_date" timestamp with time zone NOT NULL,
    "interval" smallint DEFAULT '1'::smallint NOT NULL,
    "description" "text",
    "min_participants" integer NOT NULL,
    "recurrence" "public"."recurrence" NOT NULL,
    "start_date" timestamp with time zone NOT NULL
);

ALTER TABLE "public"."ACTIVITIES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES_CATEGORIES" (
    "id_activity" bigint NOT NULL,
    "id_category" bigint NOT NULL
);

ALTER TABLE "public"."ACTIVITIES_CATEGORIES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES_USERS" (
    "id_activity" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_user" integer NOT NULL,
    "active" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."ACTIVITIES_USERS" OWNER TO "postgres";

ALTER TABLE "public"."ACTIVITIES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ACTIVITIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ACTIVITY_TEAMS" (
    "id_activity" bigint NOT NULL,
    "id_user" integer NOT NULL
);

ALTER TABLE "public"."ACTIVITY_TEAMS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ADDRESSES" (
    "id" bigint NOT NULL,
    "road" "text" NOT NULL,
    "postal_code" "text" NOT NULL,
    "complement" "text",
    "city" "text" NOT NULL,
    "number" integer NOT NULL,
    "name" "text",
    "id_lease" bigint
);

ALTER TABLE "public"."ADDRESSES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ADDRESSES_MATERIALS" (
    "quantity" integer NOT NULL,
    "id_material" bigint NOT NULL,
    "id_address" bigint NOT NULL
);

ALTER TABLE "public"."ADDRESSES_MATERIALS" OWNER TO "postgres";

ALTER TABLE "public"."ADDRESSES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ADDRESSES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."APPLICATIONS" (
    "id" bigint NOT NULL,
    "nature" "text" NOT NULL,
    "reason" "text" NOT NULL,
    "reply" integer DEFAULT 0 NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."APPLICATIONS" OWNER TO "postgres";

ALTER TABLE "public"."APPLICATIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."APPLICATIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."CATEGORIES" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."CATEGORIES" OWNER TO "postgres";

ALTER TABLE "public"."CATEGORIES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CATEGORIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."COMMENTS" (
    "id" integer NOT NULL,
    "content" "text" NOT NULL,
    "id_response" integer,
    "id_post" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "id_activity" bigint,
    "id_user" integer NOT NULL
);

ALTER TABLE "public"."COMMENTS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."COMMENTS_REACTIONS" (
    "id_user" integer NOT NULL,
    "id_comment" integer NOT NULL,
    "reaction" "text",
    "like" boolean
);

ALTER TABLE "public"."COMMENTS_REACTIONS" OWNER TO "postgres";

ALTER TABLE "public"."COMMENTS_REACTIONS" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENTS_REACTIONS_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."COMMENTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."DONATIONS" (
    "id" bigint NOT NULL,
    "money" bigint,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."DONATIONS" OWNER TO "postgres";

ALTER TABLE "public"."DONATIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DONATIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."EVENTS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "id_user" integer NOT NULL
);

ALTER TABLE "public"."EVENTS" OWNER TO "postgres";

ALTER TABLE "public"."EVENTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."EVENTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."LANDLORD" (
    "id" bigint NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text" NOT NULL
);

ALTER TABLE "public"."LANDLORD" OWNER TO "postgres";

ALTER TABLE "public"."LANDLORD" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."LANDLORD_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."LEASE" (
    "id" bigint NOT NULL,
    "rent" integer NOT NULL,
    "payment_date" timestamp with time zone NOT NULL,
    "start_lease" timestamp with time zone NOT NULL,
    "end_lease" timestamp with time zone NOT NULL,
    "id_landlord" bigint NOT NULL
);

ALTER TABLE "public"."LEASE" OWNER TO "postgres";

ALTER TABLE "public"."LEASE" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."LEASE_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."MATCHES" (
    "id" bigint NOT NULL,
    "end_time" timestamp with time zone,
    "start_time" timestamp with time zone
);

ALTER TABLE "public"."MATCHES" OWNER TO "postgres";

ALTER TABLE "public"."MATCHES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MATCHES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."MATERIALS" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "weight_grams" real
);

ALTER TABLE "public"."MATERIALS" OWNER TO "postgres";

ALTER TABLE "public"."MATERIALS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MATERIALS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."MESSAGES" (
    "id" bigint NOT NULL,
    "mesage" "text",
    "id_sender" integer NOT NULL,
    "id_receiver" integer NOT NULL,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."MESSAGES" OWNER TO "postgres";

ALTER TABLE "public"."MESSAGES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MESSAGES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."NEWS" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."NEWS" OWNER TO "postgres";

ALTER TABLE "public"."NEWS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."NEWS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POLLS" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "end_at" timestamp with time zone NOT NULL,
    "id_user" bigint NOT NULL,
    "max_choices" smallint DEFAULT '1'::smallint NOT NULL,
    "start_at" timestamp with time zone NOT NULL
);

ALTER TABLE "public"."POLLS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."POLLS_OPTIONS" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "id_poll" bigint NOT NULL
);

ALTER TABLE "public"."POLLS_OPTIONS" OWNER TO "postgres";

ALTER TABLE "public"."POLLS_OPTIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POLLS_OPTIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POLLS_VOTES" (
    "id" bigint NOT NULL,
    "id_option" bigint NOT NULL,
    "id_poll" bigint NOT NULL
);

ALTER TABLE "public"."POLLS_VOTES" OWNER TO "postgres";

ALTER TABLE "public"."POLLS_VOTES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POLLS_VOTES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."POLLS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POLLS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POSTS" (
    "id" integer NOT NULL,
    "content" "text" NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "id_user" integer NOT NULL,
    "cover_image" "text",
    "description" "text"
);

ALTER TABLE "public"."POSTS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."POSTS_CATEGORIES" (
    "id" bigint NOT NULL,
    "id_post" integer NOT NULL,
    "id_category" bigint NOT NULL
);

ALTER TABLE "public"."POSTS_CATEGORIES" OWNER TO "postgres";

ALTER TABLE "public"."POSTS_CATEGORIES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_CATEGORIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POSTS_REACTIONS" (
    "id_user" integer NOT NULL,
    "id_post" integer NOT NULL,
    "reaction" "public"."reaction" DEFAULT 'like'::"public"."reaction"
);

ALTER TABLE "public"."POSTS_REACTIONS" OWNER TO "postgres";

ALTER TABLE "public"."POSTS_REACTIONS" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_REACTIONS_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POSTS_VIEWS" (
    "id_user" integer NOT NULL,
    "viewed" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_post" integer NOT NULL
);

ALTER TABLE "public"."POSTS_VIEWS" OWNER TO "postgres";

ALTER TABLE "public"."POSTS_VIEWS" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_VIEWS_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."POSTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."PRODUCTS" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "price" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "id_seller" integer NOT NULL,
    "id_buyer" integer
);

ALTER TABLE "public"."PRODUCTS" OWNER TO "postgres";

ALTER TABLE "public"."PRODUCTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PRODUCTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."PROPOSALS" (
    "id" bigint NOT NULL,
    "proposal" "text" NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."PROPOSALS" OWNER TO "postgres";

ALTER TABLE "public"."PROPOSALS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PROPOSALS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."REASONS" (
    "id" bigint NOT NULL,
    "reason" "text" NOT NULL
);

ALTER TABLE "public"."REASONS" OWNER TO "postgres";

ALTER TABLE "public"."REASONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."REASONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."REPORTS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_reason" smallint NOT NULL,
    "content" "text" NOT NULL,
    "id_post" integer,
    "id_comment" integer
);

ALTER TABLE "public"."REPORTS" OWNER TO "postgres";

ALTER TABLE "public"."REPORTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."REPORTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."RESERVED" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "quantity" integer NOT NULL,
    "date_reserved" "date" NOT NULL,
    "id_material" bigint,
    "id_activity" bigint,
    "id_tournament" bigint,
    "id" bigint NOT NULL
);

ALTER TABLE "public"."RESERVED" OWNER TO "postgres";

ALTER TABLE "public"."RESERVED" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RESERVED_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ROLES" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."ROLES" OWNER TO "postgres";

ALTER TABLE "public"."ROLES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ROLES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."SPORTS" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "image" "text",
    "max_players" integer,
    "min_players" integer DEFAULT 1 NOT NULL
);

ALTER TABLE "public"."SPORTS" OWNER TO "postgres";

ALTER TABLE "public"."SPORTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SPORTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."TEAMS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "id_tournament" bigint NOT NULL
);

ALTER TABLE "public"."TEAMS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."TEAMS_MATCHES" (
    "winner" boolean,
    "id_team" bigint NOT NULL,
    "id_match" bigint NOT NULL
);

ALTER TABLE "public"."TEAMS_MATCHES" OWNER TO "postgres";

ALTER TABLE "public"."TEAMS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TEAMS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."TOURNAMENTS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "default_match_length" integer,
    "name" "text" NOT NULL,
    "max_participants" integer NOT NULL,
    "team_capacity" integer NOT NULL,
    "rules" "text",
    "prize" "text",
    "id_address" bigint
);

ALTER TABLE "public"."TOURNAMENTS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."TOURNAMENTS_MATCHES" (
    "id_match" bigint NOT NULL,
    "id_tournament" bigint NOT NULL,
    "round" integer NOT NULL
);

ALTER TABLE "public"."TOURNAMENTS_MATCHES" OWNER TO "postgres";

ALTER TABLE "public"."TOURNAMENTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TOURNAMENTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."USERS" (
    "id" integer NOT NULL,
    "email" character varying(255) NOT NULL,
    "username" "text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "id_referer" integer,
    "id_auth" "uuid",
    "date_validity" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL,
    "deleted_at" timestamp with time zone
);

ALTER TABLE "public"."USERS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."USERS_ROLES" (
    "id_user" integer NOT NULL,
    "id_role" integer NOT NULL
);

ALTER TABLE "public"."USERS_ROLES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."USERS_TEAMS" (
    "information" "text",
    "position" "text",
    "id_user" integer NOT NULL,
    "id_team" bigint NOT NULL
);

ALTER TABLE "public"."USERS_TEAMS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."USERS_VOTES" (
    "id" bigint NOT NULL,
    "user" "text" NOT NULL,
    "id_poll" bigint NOT NULL
);

ALTER TABLE "public"."USERS_VOTES" OWNER TO "postgres";

ALTER TABLE "public"."USERS_VOTES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."USERS_VOTES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."USERS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."USERS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "ACTIVITIES_CATEGORIES_pkey" PRIMARY KEY ("id_activity", "id_category");

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "ACTIVITIES_USERS_pkey" PRIMARY KEY ("id_activity", "id_user");

ALTER TABLE ONLY "public"."ACTIVITIES"
    ADD CONSTRAINT "ACTIVITIES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."ACTIVITY_TEAMS"
    ADD CONSTRAINT "ACTIVITY_TEAMS_pkey" PRIMARY KEY ("id_activity", "id_user");

ALTER TABLE ONLY "public"."ADDRESSES_MATERIALS"
    ADD CONSTRAINT "ADDRESSES_MATERIALS_pkey" PRIMARY KEY ("id_material", "id_address");

ALTER TABLE ONLY "public"."ADDRESSES"
    ADD CONSTRAINT "ADDRESS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."APPLICATIONS"
    ADD CONSTRAINT "APPLICATIONS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."CATEGORIES"
    ADD CONSTRAINT "CATEGORIES_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."CATEGORIES"
    ADD CONSTRAINT "CATEGORIES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "COMMENTS_REACTIONS_pkey" PRIMARY KEY ("id_user", "id_comment");

ALTER TABLE ONLY "public"."DONATIONS"
    ADD CONSTRAINT "DONATIONS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."EVENTS"
    ADD CONSTRAINT "EVENTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."LANDLORD"
    ADD CONSTRAINT "LANDLORD_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."LEASE"
    ADD CONSTRAINT "LEASE_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."MATCHES"
    ADD CONSTRAINT "MATCHES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."MATERIALS"
    ADD CONSTRAINT "MATERIALS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "MESSAGES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."NEWS"
    ADD CONSTRAINT "NEWS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POLLS_OPTIONS"
    ADD CONSTRAINT "POLLS_ANSWERS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POLLS_VOTES"
    ADD CONSTRAINT "POLLS_VOTES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POLLS"
    ADD CONSTRAINT "POLLS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POSTS_CATEGORIES"
    ADD CONSTRAINT "POSTS_CATEGORIES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "POSTS_LIKES_pkey" PRIMARY KEY ("id_user", "id_post");

ALTER TABLE ONLY "public"."POSTS_VIEWS"
    ADD CONSTRAINT "POSTS_VIEWS_pkey" PRIMARY KEY ("id_user", "id_post");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "PRODUCTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PROPOSALS"
    ADD CONSTRAINT "PROPOSALS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."REASONS"
    ADD CONSTRAINT "REASONS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."REPORTS"
    ADD CONSTRAINT "REPORTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."RESERVED"
    ADD CONSTRAINT "RESERVED_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."SPORTS"
    ADD CONSTRAINT "SPORTS_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."SPORTS"
    ADD CONSTRAINT "SPORTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."TEAMS_MATCHES"
    ADD CONSTRAINT "TEAMS_MATCHES_pkey" PRIMARY KEY ("id_team", "id_match");

ALTER TABLE ONLY "public"."TEAMS"
    ADD CONSTRAINT "TEAMS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."TOURNAMENTS_MATCHES"
    ADD CONSTRAINT "TOURNAMENTS_MATCHES_pkey" PRIMARY KEY ("id_match", "id_tournament");

ALTER TABLE ONLY "public"."TOURNAMENTS"
    ADD CONSTRAINT "TOURNAMENTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."USERS_ROLES"
    ADD CONSTRAINT "USERS_ROLES_pkey" PRIMARY KEY ("id_user", "id_role");

ALTER TABLE ONLY "public"."USERS_TEAMS"
    ADD CONSTRAINT "USERS_TEAMS_pkey" PRIMARY KEY ("id_user", "id_team");

ALTER TABLE ONLY "public"."USERS_VOTES"
    ADD CONSTRAINT "USERS_VOTES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "USERS_id_auth_key" UNIQUE ("id_auth");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POSTS"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."ROLES"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

CREATE INDEX "POSTS_id_idx" ON "public"."POSTS" USING "btree" ("id");

ALTER TABLE ONLY "public"."ACTIVITY_TEAMS"
    ADD CONSTRAINT "ACTIVITY_TEAM_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."ACTIVITY_TEAMS"
    ADD CONSTRAINT "ACTIVITY_TEAM_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POSTS_CATEGORIES"
    ADD CONSTRAINT "POSTS_CATEGORIES_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES "public"."CATEGORIES"("id");

ALTER TABLE ONLY "public"."POSTS_CATEGORIES"
    ADD CONSTRAINT "POSTS_CATEGORIES_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."POSTS_VIEWS"
    ADD CONSTRAINT "POSTS_VIEWS_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."POSTS_VIEWS"
    ADD CONSTRAINT "POSTS_VIEWS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."REPORTS"
    ADD CONSTRAINT "REPORTS_id_comment_fkey" FOREIGN KEY ("id_comment") REFERENCES "public"."COMMENTS"("id");

ALTER TABLE ONLY "public"."REPORTS"
    ADD CONSTRAINT "REPORTS_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."REPORTS"
    ADD CONSTRAINT "REPORTS_id_reason_fkey" FOREIGN KEY ("id_reason") REFERENCES "public"."REASONS"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "comments_id_comment_fkey" FOREIGN KEY ("id_response") REFERENCES "public"."COMMENTS"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "public_ACTIVITIES_CATEGORIES_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "public_ACTIVITIES_CATEGORIES_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES "public"."CATEGORIES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "public_ACTIVITIES_USERS_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "public_ACTIVITIES_USERS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ACTIVITIES"
    ADD CONSTRAINT "public_ACTIVITIES_id_address_fkey" FOREIGN KEY ("id_address") REFERENCES "public"."ADDRESSES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES"
    ADD CONSTRAINT "public_ACTIVITIES_id_sport_fkey" FOREIGN KEY ("id_sport") REFERENCES "public"."SPORTS"("id");

ALTER TABLE ONLY "public"."ADDRESSES_MATERIALS"
    ADD CONSTRAINT "public_ADDRESSES_MATERIALS_id_address_fkey" FOREIGN KEY ("id_address") REFERENCES "public"."ADDRESSES"("id");

ALTER TABLE ONLY "public"."ADDRESSES_MATERIALS"
    ADD CONSTRAINT "public_ADDRESSES_MATERIALS_id_material_fkey" FOREIGN KEY ("id_material") REFERENCES "public"."MATERIALS"("id");

ALTER TABLE ONLY "public"."ADDRESSES"
    ADD CONSTRAINT "public_ADDRESS_id_lease_fkey" FOREIGN KEY ("id_lease") REFERENCES "public"."LEASE"("id");

ALTER TABLE ONLY "public"."APPLICATIONS"
    ADD CONSTRAINT "public_APPLICATIONS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "public_COMMENTS_LIKES_id_comment_fkey" FOREIGN KEY ("id_comment") REFERENCES "public"."COMMENTS"("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "public_COMMENTS_LIKES_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "public_COMMENTS_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "public_COMMENTS_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "public_COMMENTS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."DONATIONS"
    ADD CONSTRAINT "public_DONATIONS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."EVENTS"
    ADD CONSTRAINT "public_EVENTS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."LEASE"
    ADD CONSTRAINT "public_LEASE_id_landlord_fkey" FOREIGN KEY ("id_landlord") REFERENCES "public"."LANDLORD"("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "public_MESSAGES_id_receiver_fkey" FOREIGN KEY ("id_receiver") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "public_MESSAGES_id_sender_fkey" FOREIGN KEY ("id_sender") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."NEWS"
    ADD CONSTRAINT "public_NEWS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POLLS_OPTIONS"
    ADD CONSTRAINT "public_POLLS_OPTIONS_id_poll_fkey" FOREIGN KEY ("id_poll") REFERENCES "public"."POLLS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."POLLS_VOTES"
    ADD CONSTRAINT "public_POLLS_VOTES_id_option_fkey" FOREIGN KEY ("id_option") REFERENCES "public"."POLLS_OPTIONS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."POLLS_VOTES"
    ADD CONSTRAINT "public_POLLS_VOTES_id_poll_fkey" FOREIGN KEY ("id_poll") REFERENCES "public"."POLLS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."POLLS"
    ADD CONSTRAINT "public_POLLS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "public_POSTS_LIKES_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "public_POSTS_LIKES_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POSTS"
    ADD CONSTRAINT "public_POSTS_user_id_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "public_PRODUCTS_id_buyer_fkey" FOREIGN KEY ("id_buyer") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "public_PRODUCTS_id_user_fkey" FOREIGN KEY ("id_seller") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PROPOSALS"
    ADD CONSTRAINT "public_PROPOSALS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."RESERVED"
    ADD CONSTRAINT "public_RESERVED_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."RESERVED"
    ADD CONSTRAINT "public_RESERVED_id_material_fkey" FOREIGN KEY ("id_material") REFERENCES "public"."MATERIALS"("id");

ALTER TABLE ONLY "public"."RESERVED"
    ADD CONSTRAINT "public_RESERVED_id_tournament_fkey" FOREIGN KEY ("id_tournament") REFERENCES "public"."TOURNAMENTS"("id");

ALTER TABLE ONLY "public"."TEAMS_MATCHES"
    ADD CONSTRAINT "public_TEAMS_MATCHES_id_match_fkey" FOREIGN KEY ("id_match") REFERENCES "public"."MATCHES"("id");

ALTER TABLE ONLY "public"."TEAMS_MATCHES"
    ADD CONSTRAINT "public_TEAMS_MATCHES_id_team_fkey" FOREIGN KEY ("id_team") REFERENCES "public"."TEAMS"("id");

ALTER TABLE ONLY "public"."TEAMS"
    ADD CONSTRAINT "public_TEAMS_id_tournament_fkey" FOREIGN KEY ("id_tournament") REFERENCES "public"."TOURNAMENTS"("id");

ALTER TABLE ONLY "public"."TOURNAMENTS_MATCHES"
    ADD CONSTRAINT "public_TOURNAMENTS_MATCHES_id_match_fkey" FOREIGN KEY ("id_match") REFERENCES "public"."MATCHES"("id");

ALTER TABLE ONLY "public"."TOURNAMENTS_MATCHES"
    ADD CONSTRAINT "public_TOURNAMENTS_MATCHES_id_tournament_fkey" FOREIGN KEY ("id_tournament") REFERENCES "public"."TOURNAMENTS"("id");

ALTER TABLE ONLY "public"."TOURNAMENTS"
    ADD CONSTRAINT "public_TOURNAMENTS_id_address_fkey" FOREIGN KEY ("id_address") REFERENCES "public"."TOURNAMENTS"("id");

ALTER TABLE ONLY "public"."USERS_ROLES"
    ADD CONSTRAINT "public_USERS_ROLES_id_role_fkey" FOREIGN KEY ("id_role") REFERENCES "public"."ROLES"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."USERS_ROLES"
    ADD CONSTRAINT "public_USERS_ROLES_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."USERS_TEAMS"
    ADD CONSTRAINT "public_USERS_TEAMS_id_team_fkey" FOREIGN KEY ("id_team") REFERENCES "public"."TEAMS"("id");

ALTER TABLE ONLY "public"."USERS_TEAMS"
    ADD CONSTRAINT "public_USERS_TEAMS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."USERS_VOTES"
    ADD CONSTRAINT "public_USERS_VOTES_id_poll_fkey" FOREIGN KEY ("id_poll") REFERENCES "public"."POLLS"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "public_USERS_id_auth_fkey" FOREIGN KEY ("id_auth") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_id_referer_fkey" FOREIGN KEY ("id_referer") REFERENCES "public"."USERS"("id");

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITY_TEAMS" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITY_TEAMS" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITY_TEAMS" TO "service_role";

GRANT ALL ON TABLE "public"."ADDRESSES" TO "anon";
GRANT ALL ON TABLE "public"."ADDRESSES" TO "authenticated";
GRANT ALL ON TABLE "public"."ADDRESSES" TO "service_role";

GRANT ALL ON TABLE "public"."ADDRESSES_MATERIALS" TO "anon";
GRANT ALL ON TABLE "public"."ADDRESSES_MATERIALS" TO "authenticated";
GRANT ALL ON TABLE "public"."ADDRESSES_MATERIALS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ADDRESSES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ADDRESSES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ADDRESSES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."APPLICATIONS" TO "anon";
GRANT ALL ON TABLE "public"."APPLICATIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."APPLICATIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."CATEGORIES" TO "anon";
GRANT ALL ON TABLE "public"."CATEGORIES" TO "authenticated";
GRANT ALL ON TABLE "public"."CATEGORIES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."COMMENTS" TO "anon";
GRANT ALL ON TABLE "public"."COMMENTS" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENTS" TO "service_role";

GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "anon";
GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."COMMENTS_REACTIONS_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENTS_REACTIONS_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENTS_REACTIONS_id_user_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."DONATIONS" TO "anon";
GRANT ALL ON TABLE "public"."DONATIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."DONATIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."EVENTS" TO "anon";
GRANT ALL ON TABLE "public"."EVENTS" TO "authenticated";
GRANT ALL ON TABLE "public"."EVENTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."LANDLORD" TO "anon";
GRANT ALL ON TABLE "public"."LANDLORD" TO "authenticated";
GRANT ALL ON TABLE "public"."LANDLORD" TO "service_role";

GRANT ALL ON SEQUENCE "public"."LANDLORD_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."LANDLORD_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."LANDLORD_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."LEASE" TO "anon";
GRANT ALL ON TABLE "public"."LEASE" TO "authenticated";
GRANT ALL ON TABLE "public"."LEASE" TO "service_role";

GRANT ALL ON SEQUENCE "public"."LEASE_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."LEASE_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."LEASE_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."MATCHES" TO "anon";
GRANT ALL ON TABLE "public"."MATCHES" TO "authenticated";
GRANT ALL ON TABLE "public"."MATCHES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."MATCHES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MATCHES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MATCHES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."MATERIALS" TO "anon";
GRANT ALL ON TABLE "public"."MATERIALS" TO "authenticated";
GRANT ALL ON TABLE "public"."MATERIALS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."MATERIALS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MATERIALS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MATERIALS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."MESSAGES" TO "anon";
GRANT ALL ON TABLE "public"."MESSAGES" TO "authenticated";
GRANT ALL ON TABLE "public"."MESSAGES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."NEWS" TO "anon";
GRANT ALL ON TABLE "public"."NEWS" TO "authenticated";
GRANT ALL ON TABLE "public"."NEWS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POLLS" TO "anon";
GRANT ALL ON TABLE "public"."POLLS" TO "authenticated";
GRANT ALL ON TABLE "public"."POLLS" TO "service_role";

GRANT ALL ON TABLE "public"."POLLS_OPTIONS" TO "anon";
GRANT ALL ON TABLE "public"."POLLS_OPTIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."POLLS_OPTIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POLLS_OPTIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POLLS_OPTIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POLLS_OPTIONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POLLS_VOTES" TO "anon";
GRANT ALL ON TABLE "public"."POLLS_VOTES" TO "authenticated";
GRANT ALL ON TABLE "public"."POLLS_VOTES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POLLS_VOTES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POLLS_VOTES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POLLS_VOTES_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS" TO "anon";
GRANT ALL ON TABLE "public"."POSTS" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS_CATEGORIES" TO "anon";
GRANT ALL ON TABLE "public"."POSTS_CATEGORIES" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS_CATEGORIES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_CATEGORIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_CATEGORIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_CATEGORIES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "anon";
GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_REACTIONS_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_REACTIONS_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_REACTIONS_id_user_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS_VIEWS" TO "anon";
GRANT ALL ON TABLE "public"."POSTS_VIEWS" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS_VIEWS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_VIEWS_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_VIEWS_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_VIEWS_id_user_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."PRODUCTS" TO "anon";
GRANT ALL ON TABLE "public"."PRODUCTS" TO "authenticated";
GRANT ALL ON TABLE "public"."PRODUCTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."PROPOSALS" TO "anon";
GRANT ALL ON TABLE "public"."PROPOSALS" TO "authenticated";
GRANT ALL ON TABLE "public"."PROPOSALS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."REASONS" TO "anon";
GRANT ALL ON TABLE "public"."REASONS" TO "authenticated";
GRANT ALL ON TABLE "public"."REASONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."REASONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."REASONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."REASONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."REPORTS" TO "anon";
GRANT ALL ON TABLE "public"."REPORTS" TO "authenticated";
GRANT ALL ON TABLE "public"."REPORTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."REPORTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."REPORTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."REPORTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."RESERVED" TO "anon";
GRANT ALL ON TABLE "public"."RESERVED" TO "authenticated";
GRANT ALL ON TABLE "public"."RESERVED" TO "service_role";

GRANT ALL ON SEQUENCE "public"."RESERVED_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RESERVED_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RESERVED_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."ROLES" TO "anon";
GRANT ALL ON TABLE "public"."ROLES" TO "authenticated";
GRANT ALL ON TABLE "public"."ROLES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ROLES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ROLES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ROLES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."SPORTS" TO "anon";
GRANT ALL ON TABLE "public"."SPORTS" TO "authenticated";
GRANT ALL ON TABLE "public"."SPORTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."TEAMS" TO "anon";
GRANT ALL ON TABLE "public"."TEAMS" TO "authenticated";
GRANT ALL ON TABLE "public"."TEAMS" TO "service_role";

GRANT ALL ON TABLE "public"."TEAMS_MATCHES" TO "anon";
GRANT ALL ON TABLE "public"."TEAMS_MATCHES" TO "authenticated";
GRANT ALL ON TABLE "public"."TEAMS_MATCHES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."TEAMS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TEAMS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TEAMS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."TOURNAMENTS" TO "anon";
GRANT ALL ON TABLE "public"."TOURNAMENTS" TO "authenticated";
GRANT ALL ON TABLE "public"."TOURNAMENTS" TO "service_role";

GRANT ALL ON TABLE "public"."TOURNAMENTS_MATCHES" TO "anon";
GRANT ALL ON TABLE "public"."TOURNAMENTS_MATCHES" TO "authenticated";
GRANT ALL ON TABLE "public"."TOURNAMENTS_MATCHES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."TOURNAMENTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TOURNAMENTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TOURNAMENTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."USERS" TO "anon";
GRANT ALL ON TABLE "public"."USERS" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS" TO "service_role";

GRANT ALL ON TABLE "public"."USERS_ROLES" TO "anon";
GRANT ALL ON TABLE "public"."USERS_ROLES" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS_ROLES" TO "service_role";

GRANT ALL ON TABLE "public"."USERS_TEAMS" TO "anon";
GRANT ALL ON TABLE "public"."USERS_TEAMS" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS_TEAMS" TO "service_role";

GRANT ALL ON TABLE "public"."USERS_VOTES" TO "anon";
GRANT ALL ON TABLE "public"."USERS_VOTES" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS_VOTES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."USERS_VOTES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."USERS_VOTES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."USERS_VOTES_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
