apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlonix-admin
  labels:
    app: athlonix-admin

spec:
  replicas: 2
  selector:
    matchLabels:
      app: athlonix-admin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athlonix-admin
    spec:
      containers:
      - name: athlonix-admin
        image: ghcr.io/athlonix/athlonix/admin:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3100
        env:
          - name: PORT
            value: "3100"
          - name: NEXT_PUBLIC_ATHLONIX_API_URL
            value: "http://athlonix-api:3101"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: docker-athlonix
