apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlonix-admin
  labels:
    app: athlonix
spec:
  selector:
    matchLabels:
      app: athlonix
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athlonix
    spec:
      containers:
        - name: athlonix-admin
          image: 'ghcr.io/athlonix/athlonix/admin:latest'
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - containerPort: 3100
          env:
            - name: ATHLONIX_API_URL
              value: 'http://athlonix-api:3101'
            - name: PORT
              value: '3100'
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
      imagePullSecrets:
        - name: docker-athlonix
