apiVersion: v1
kind: Service
metadata:
  name: athlonix-admin
spec:
  selector:
    app: athlonix-admin
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 31000
  type: NodePort
