apiVersion: v1
kind: Service
metadata:
  name: athlonix-admin
  namespace: default
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
    nodePort: 31000
  selector:
    app: athlonix
  type: NodePort
