apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlonix-api
  labels:
    app: athlonix-api
spec:
  selector:
    matchLabels:
      app: athlonix-api
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athlonix-api
    spec:
      containers:
        - name: athlonix-api
          image: 'ghcr.io/athlonix/athlonix/api:latest'
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          envFrom:
            - secretRef:
                name: athlonix-api-env
          ports:
            - containerPort: 3101
          env:
            - name: PORT
              value: '3101'
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
            requests:
              memory: "128Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: docker-athlonix
