apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlonix-api
  labels:
    app: athlonix
spec:
  selector:
    matchLabels:
      app: athlonix
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athlonix
        octopusexport: OctopusExport
    spec:
      containers:
        - name: athlonix-api
          image: 'ghcr.io/athlonix/athlonix/api:latest'
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          envFrom:
            - secretRef:
                name: athlonix-api-env
          ports:
            - containerPort: 3101
          env:
            - name: PORT
              value: '3101'
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
      imagePullSecrets:
        - name: docker-athlonix
