apiVersion: v1
kind: Service
metadata:
  name: athlonix-api
spec:
  selector:
    app: athlonix-api
  ports:
    - protocol: TCP
      port: 3101
      targetPort: 3101
      nodePort: 31001
  type: NodePort
