apiVersion: v1
kind: Service
metadata:
  name: athlonix-api
  namespace: default
spec:
  ports:
  - name: http
    port: 3101
    protocol: TCP
    targetPort: 3101
    nodePort: 31001
  selector:
    app: athlonix
  type: NodePort
