apiVersion: apps/v1
kind: Deployment
metadata:
  name: athlonix-client
  labels:
    app: athlonix-client

spec:
  replicas: 2
  selector:
    matchLabels:
      app: athlonix-client
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: athlonix-client
    spec:
      containers:
      - name: athlonix-client
        image: ghcr.io/athlonix/athlonix/client:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3102
        env:
          - name: PORT
            value: "3102"
          - name: API_URL
            value: "http://athlonix-api:3101"
          - name: NEXT_PUBLIC_API_URL
            value: "https://athlonix-api.jayllyz.fr"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: docker-athlonix
