apiVersion: v1
kind: Service
metadata:
  name: athlonix-client
spec:
  selector:
    app: athlonix-client
  ports:
    - protocol: TCP
      port: 3102
      targetPort: 3102
      nodePort: 31002
  type: NodePort
