create table "public"."DOCUMENTS" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "owner" integer not null,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX "DOCUMENTS_pkey" ON public."DOCUMENTS" USING btree (id);

alter table "public"."DOCUMENTS" add constraint "DOCUMENTS_pkey" PRIMARY KEY using index "DOCUMENTS_pkey";

alter table "public"."DOCUMENTS" add constraint "DOCUMENTS_owner_fkey" FOREIGN KEY (owner) REFERENCES "USERS"(id) not valid;

alter table "public"."DOCUMENTS" validate constraint "DOCUMENTS_owner_fkey";

grant delete on table "public"."DOCUMENTS" to "anon";

grant insert on table "public"."DOCUMENTS" to "anon";

grant references on table "public"."DOCUMENTS" to "anon";

grant select on table "public"."DOCUMENTS" to "anon";

grant trigger on table "public"."DOCUMENTS" to "anon";

grant truncate on table "public"."DOCUMENTS" to "anon";

grant update on table "public"."DOCUMENTS" to "anon";

grant delete on table "public"."DOCUMENTS" to "authenticated";

grant insert on table "public"."DOCUMENTS" to "authenticated";

grant references on table "public"."DOCUMENTS" to "authenticated";

grant select on table "public"."DOCUMENTS" to "authenticated";

grant trigger on table "public"."DOCUMENTS" to "authenticated";

grant truncate on table "public"."DOCUMENTS" to "authenticated";

grant update on table "public"."DOCUMENTS" to "authenticated";

grant delete on table "public"."DOCUMENTS" to "service_role";

grant insert on table "public"."DOCUMENTS" to "service_role";

grant references on table "public"."DOCUMENTS" to "service_role";

grant select on table "public"."DOCUMENTS" to "service_role";

grant trigger on table "public"."DOCUMENTS" to "service_role";

grant truncate on table "public"."DOCUMENTS" to "service_role";

grant update on table "public"."DOCUMENTS" to "service_role";
