create table "public"."ASSEMBLIES" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "date" timestamp with time zone not null,
    "location" bigint,
    "lawsuit" text
);


create table "public"."ASSEMBLIES_ATTENDEES" (
    "id" bigint generated by default as identity not null,
    "id_assembly" bigint,
    "id_member" integer
);

CREATE UNIQUE INDEX "ASSEMBLIES_ATTENDEES_pkey" ON public."ASSEMBLIES_ATTENDEES" USING btree (id);

CREATE UNIQUE INDEX "ASSEMBLIES_pkey" ON public."ASSEMBLIES" USING btree (id);

alter table "public"."ASSEMBLIES" add constraint "ASSEMBLIES_pkey" PRIMARY KEY using index "ASSEMBLIES_pkey";

alter table "public"."ASSEMBLIES_ATTENDEES" add constraint "ASSEMBLIES_ATTENDEES_pkey" PRIMARY KEY using index "ASSEMBLIES_ATTENDEES_pkey";

alter table "public"."POLLS" add column "assembly" bigint;
