revoke delete on table "public"."POLLS_ANSWERS" from "anon";

revoke insert on table "public"."POLLS_ANSWERS" from "anon";

revoke references on table "public"."POLLS_ANSWERS" from "anon";

revoke select on table "public"."POLLS_ANSWERS" from "anon";

revoke trigger on table "public"."POLLS_ANSWERS" from "anon";

revoke truncate on table "public"."POLLS_ANSWERS" from "anon";

revoke update on table "public"."POLLS_ANSWERS" from "anon";

revoke delete on table "public"."POLLS_ANSWERS" from "authenticated";

revoke insert on table "public"."POLLS_ANSWERS" from "authenticated";

revoke references on table "public"."POLLS_ANSWERS" from "authenticated";

revoke select on table "public"."POLLS_ANSWERS" from "authenticated";

revoke trigger on table "public"."POLLS_ANSWERS" from "authenticated";

revoke truncate on table "public"."POLLS_ANSWERS" from "authenticated";

revoke update on table "public"."POLLS_ANSWERS" from "authenticated";

revoke delete on table "public"."POLLS_ANSWERS" from "service_role";

revoke insert on table "public"."POLLS_ANSWERS" from "service_role";

revoke references on table "public"."POLLS_ANSWERS" from "service_role";

revoke select on table "public"."POLLS_ANSWERS" from "service_role";

revoke trigger on table "public"."POLLS_ANSWERS" from "service_role";

revoke truncate on table "public"."POLLS_ANSWERS" from "service_role";

revoke update on table "public"."POLLS_ANSWERS" from "service_role";

alter table "public"."POLLS_ANSWERS" drop constraint "public_POLLS_ANSWERS_id_poll_fkey";

alter table "public"."POLLS_ANSWERS" drop constraint "POLLS_ANSWERS_pkey";

drop index if exists "public"."POLLS_ANSWERS_pkey";

drop table "public"."POLLS_ANSWERS";

create table "public"."POLLS_OPTIONS" (
    "id" bigint generated by default as identity not null,
    "content" text not null,
    "id_poll" bigint not null
);


create table "public"."POLLS_VOTES" (
    "id" bigint generated by default as identity not null,
    "id_option" bigint not null,
    "id_poll" bigint not null
);


create table "public"."USERS_VOTES" (
    "id" bigint generated by default as identity not null,
    "user" text not null,
    "id_poll" bigint not null
);


alter table "public"."POLLS" drop column "content";

alter table "public"."POLLS" add column "description" text;

alter table "public"."POLLS" add column "end_at" timestamp with time zone;

alter table "public"."POLLS" add column "id_user" bigint not null;

alter table "public"."POLLS" add column "max_choices" smallint not null default '1'::smallint;

alter table "public"."POLLS" add column "start_at" timestamp with time zone;

CREATE UNIQUE INDEX "POLLS_VOTES_pkey" ON public."POLLS_VOTES" USING btree (id);

CREATE UNIQUE INDEX "USERS_VOTES_pkey" ON public."USERS_VOTES" USING btree (id);

CREATE UNIQUE INDEX "POLLS_ANSWERS_pkey" ON public."POLLS_OPTIONS" USING btree (id);

alter table "public"."POLLS_OPTIONS" add constraint "POLLS_ANSWERS_pkey" PRIMARY KEY using index "POLLS_ANSWERS_pkey";

alter table "public"."POLLS_VOTES" add constraint "POLLS_VOTES_pkey" PRIMARY KEY using index "POLLS_VOTES_pkey";

alter table "public"."USERS_VOTES" add constraint "USERS_VOTES_pkey" PRIMARY KEY using index "USERS_VOTES_pkey";

alter table "public"."POLLS" add constraint "public_POLLS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."POLLS" validate constraint "public_POLLS_id_user_fkey";

alter table "public"."POLLS_OPTIONS" add constraint "public_POLLS_OPTIONS_id_poll_fkey" FOREIGN KEY (id_poll) REFERENCES "POLLS"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."POLLS_OPTIONS" validate constraint "public_POLLS_OPTIONS_id_poll_fkey";

alter table "public"."POLLS_VOTES" add constraint "public_POLLS_VOTES_id_option_fkey" FOREIGN KEY (id_option) REFERENCES "POLLS_OPTIONS"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."POLLS_VOTES" validate constraint "public_POLLS_VOTES_id_option_fkey";

alter table "public"."POLLS_VOTES" add constraint "public_POLLS_VOTES_id_poll_fkey" FOREIGN KEY (id_poll) REFERENCES "POLLS"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."POLLS_VOTES" validate constraint "public_POLLS_VOTES_id_poll_fkey";

alter table "public"."USERS_VOTES" add constraint "public_USERS_VOTES_id_poll_fkey" FOREIGN KEY (id_poll) REFERENCES "POLLS"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."USERS_VOTES" validate constraint "public_USERS_VOTES_id_poll_fkey";

grant delete on table "public"."POLLS_OPTIONS" to "anon";

grant insert on table "public"."POLLS_OPTIONS" to "anon";

grant references on table "public"."POLLS_OPTIONS" to "anon";

grant select on table "public"."POLLS_OPTIONS" to "anon";

grant trigger on table "public"."POLLS_OPTIONS" to "anon";

grant truncate on table "public"."POLLS_OPTIONS" to "anon";

grant update on table "public"."POLLS_OPTIONS" to "anon";

grant delete on table "public"."POLLS_OPTIONS" to "authenticated";

grant insert on table "public"."POLLS_OPTIONS" to "authenticated";

grant references on table "public"."POLLS_OPTIONS" to "authenticated";

grant select on table "public"."POLLS_OPTIONS" to "authenticated";

grant trigger on table "public"."POLLS_OPTIONS" to "authenticated";

grant truncate on table "public"."POLLS_OPTIONS" to "authenticated";

grant update on table "public"."POLLS_OPTIONS" to "authenticated";

grant delete on table "public"."POLLS_OPTIONS" to "service_role";

grant insert on table "public"."POLLS_OPTIONS" to "service_role";

grant references on table "public"."POLLS_OPTIONS" to "service_role";

grant select on table "public"."POLLS_OPTIONS" to "service_role";

grant trigger on table "public"."POLLS_OPTIONS" to "service_role";

grant truncate on table "public"."POLLS_OPTIONS" to "service_role";

grant update on table "public"."POLLS_OPTIONS" to "service_role";

grant delete on table "public"."POLLS_VOTES" to "anon";

grant insert on table "public"."POLLS_VOTES" to "anon";

grant references on table "public"."POLLS_VOTES" to "anon";

grant select on table "public"."POLLS_VOTES" to "anon";

grant trigger on table "public"."POLLS_VOTES" to "anon";

grant truncate on table "public"."POLLS_VOTES" to "anon";

grant update on table "public"."POLLS_VOTES" to "anon";

grant delete on table "public"."POLLS_VOTES" to "authenticated";

grant insert on table "public"."POLLS_VOTES" to "authenticated";

grant references on table "public"."POLLS_VOTES" to "authenticated";

grant select on table "public"."POLLS_VOTES" to "authenticated";

grant trigger on table "public"."POLLS_VOTES" to "authenticated";

grant truncate on table "public"."POLLS_VOTES" to "authenticated";

grant update on table "public"."POLLS_VOTES" to "authenticated";

grant delete on table "public"."POLLS_VOTES" to "service_role";

grant insert on table "public"."POLLS_VOTES" to "service_role";

grant references on table "public"."POLLS_VOTES" to "service_role";

grant select on table "public"."POLLS_VOTES" to "service_role";

grant trigger on table "public"."POLLS_VOTES" to "service_role";

grant truncate on table "public"."POLLS_VOTES" to "service_role";

grant update on table "public"."POLLS_VOTES" to "service_role";

grant delete on table "public"."USERS_VOTES" to "anon";

grant insert on table "public"."USERS_VOTES" to "anon";

grant references on table "public"."USERS_VOTES" to "anon";

grant select on table "public"."USERS_VOTES" to "anon";

grant trigger on table "public"."USERS_VOTES" to "anon";

grant truncate on table "public"."USERS_VOTES" to "anon";

grant update on table "public"."USERS_VOTES" to "anon";

grant delete on table "public"."USERS_VOTES" to "authenticated";

grant insert on table "public"."USERS_VOTES" to "authenticated";

grant references on table "public"."USERS_VOTES" to "authenticated";

grant select on table "public"."USERS_VOTES" to "authenticated";

grant trigger on table "public"."USERS_VOTES" to "authenticated";

grant truncate on table "public"."USERS_VOTES" to "authenticated";

grant update on table "public"."USERS_VOTES" to "authenticated";

grant delete on table "public"."USERS_VOTES" to "service_role";

grant insert on table "public"."USERS_VOTES" to "service_role";

grant references on table "public"."USERS_VOTES" to "service_role";

grant select on table "public"."USERS_VOTES" to "service_role";

grant trigger on table "public"."USERS_VOTES" to "service_role";

grant truncate on table "public"."USERS_VOTES" to "service_role";

grant update on table "public"."USERS_VOTES" to "service_role";sup
