
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "isn" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES" (
    "id" bigint NOT NULL,
    "max_participants" integer NOT NULL,
    "name" "text" NOT NULL,
    "duration_minute" bigint NOT NULL,
    "id_sport" bigint
);

ALTER TABLE "public"."ACTIVITIES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES_CATEGORIES" (
    "id_activity" bigint NOT NULL,
    "id_category" bigint NOT NULL
);

ALTER TABLE "public"."ACTIVITIES_CATEGORIES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ACTIVITIES_USERS" (
    "id_activity" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_user" integer NOT NULL
);

ALTER TABLE "public"."ACTIVITIES_USERS" OWNER TO "postgres";

ALTER TABLE "public"."ACTIVITIES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ACTIVITIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."APPLICATIONS" (
    "id" bigint NOT NULL,
    "nature" "text" NOT NULL,
    "reason" "text" NOT NULL,
    "reply" integer DEFAULT 0 NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."APPLICATIONS" OWNER TO "postgres";

ALTER TABLE "public"."APPLICATIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."APPLICATIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."CATEGORIES" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."CATEGORIES" OWNER TO "postgres";

ALTER TABLE "public"."CATEGORIES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CATEGORIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."COMMENTS" (
    "id" integer NOT NULL,
    "content" "text" NOT NULL,
    "id_response" integer,
    "id_post" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "id_activity" bigint
);

ALTER TABLE "public"."COMMENTS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."COMMENTS_REACTIONS" (
    "id_user" integer NOT NULL,
    "id_comment" integer NOT NULL,
    "reaction" "text",
    "like" boolean
);

ALTER TABLE "public"."COMMENTS_REACTIONS" OWNER TO "postgres";

ALTER TABLE "public"."COMMENTS_REACTIONS" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENTS_LIKES_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."COMMENTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."DONATIONS" (
    "id" bigint NOT NULL,
    "money" bigint,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."DONATIONS" OWNER TO "postgres";

ALTER TABLE "public"."DONATIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DONATIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."EVENTS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "id_user" integer NOT NULL
);

ALTER TABLE "public"."EVENTS" OWNER TO "postgres";

ALTER TABLE "public"."EVENTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."EVENTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."MESSAGES" (
    "id" bigint NOT NULL,
    "mesage" "text",
    "id_sender" integer NOT NULL,
    "id_receiver" integer NOT NULL,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."MESSAGES" OWNER TO "postgres";

ALTER TABLE "public"."MESSAGES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MESSAGES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."NEWS" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."NEWS" OWNER TO "postgres";

ALTER TABLE "public"."NEWS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."NEWS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POLLS" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "content" "text"
);

ALTER TABLE "public"."POLLS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."POLLS_ANSWERS" (
    "id" bigint NOT NULL,
    "answer" "text" NOT NULL,
    "id_poll" bigint NOT NULL
);

ALTER TABLE "public"."POLLS_ANSWERS" OWNER TO "postgres";

ALTER TABLE "public"."POLLS_ANSWERS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POLLS_ANSWERS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."POLLS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POLLS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."POSTS" (
    "id" integer NOT NULL,
    "content" "text" NOT NULL,
    "title" "text" NOT NULL,
    "user_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."POSTS" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."POSTS_REACTIONS" (
    "id_user" integer NOT NULL,
    "id_post" integer NOT NULL,
    "reaction" "text",
    "like" boolean
);

ALTER TABLE "public"."POSTS_REACTIONS" OWNER TO "postgres";

ALTER TABLE "public"."POSTS_REACTIONS" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_LIKES_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."POSTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."POSTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."PRODUCTS" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "price" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "id_seller" integer NOT NULL,
    "id_buyer" integer
);

ALTER TABLE "public"."PRODUCTS" OWNER TO "postgres";

ALTER TABLE "public"."PRODUCTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PRODUCTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."PROPOSALS" (
    "id" bigint NOT NULL,
    "proposal" "text" NOT NULL,
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."PROPOSALS" OWNER TO "postgres";

ALTER TABLE "public"."PROPOSALS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PROPOSALS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ROLES" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."ROLES" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."SPORTS" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."SPORTS" OWNER TO "postgres";

ALTER TABLE "public"."SPORTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SPORTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."USERS" (
    "id" integer NOT NULL,
    "email" character varying(255) NOT NULL,
    "username" "text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "id_referer" integer NOT NULL,
    "id_role" integer
);

ALTER TABLE "public"."USERS" OWNER TO "postgres";

ALTER TABLE "public"."USERS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."USERS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "ACTIVITIES_CATEGORIES_pkey" PRIMARY KEY ("id_activity", "id_category");

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "ACTIVITIES_USERS_pkey" PRIMARY KEY ("id_activity", "id_user");

ALTER TABLE ONLY "public"."ACTIVITIES"
    ADD CONSTRAINT "ACTIVITIES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."APPLICATIONS"
    ADD CONSTRAINT "APPLICATIONS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."CATEGORIES"
    ADD CONSTRAINT "CATEGORIES_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."CATEGORIES"
    ADD CONSTRAINT "CATEGORIES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "COMMENTS_REACTIONS_pkey" PRIMARY KEY ("id_user", "id_comment");

ALTER TABLE ONLY "public"."DONATIONS"
    ADD CONSTRAINT "DONATIONS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."EVENTS"
    ADD CONSTRAINT "EVENTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "MESSAGES_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."NEWS"
    ADD CONSTRAINT "NEWS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POLLS_ANSWERS"
    ADD CONSTRAINT "POLLS_ANSWERS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POLLS"
    ADD CONSTRAINT "POLLS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "POSTS_LIKES_pkey" PRIMARY KEY ("id_user", "id_post");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "PRODUCTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PROPOSALS"
    ADD CONSTRAINT "PROPOSALS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."SPORTS"
    ADD CONSTRAINT "SPORTS_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."SPORTS"
    ADD CONSTRAINT "SPORTS_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."POSTS"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."ROLES"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

CREATE INDEX "POSTS_id_idx" ON "public"."POSTS" USING "btree" ("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "comments_id_comment_fkey" FOREIGN KEY ("id_response") REFERENCES "public"."COMMENTS"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "public_ACTIVITIES_CATEGORIES_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_CATEGORIES"
    ADD CONSTRAINT "public_ACTIVITIES_CATEGORIES_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES "public"."CATEGORIES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "public_ACTIVITIES_USERS_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."ACTIVITIES_USERS"
    ADD CONSTRAINT "public_ACTIVITIES_USERS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."ACTIVITIES"
    ADD CONSTRAINT "public_ACTIVITIES_id_sport_fkey" FOREIGN KEY ("id_sport") REFERENCES "public"."SPORTS"("id");

ALTER TABLE ONLY "public"."APPLICATIONS"
    ADD CONSTRAINT "public_APPLICATIONS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "public_COMMENTS_LIKES_id_comment_fkey" FOREIGN KEY ("id_comment") REFERENCES "public"."COMMENTS"("id");

ALTER TABLE ONLY "public"."COMMENTS_REACTIONS"
    ADD CONSTRAINT "public_COMMENTS_LIKES_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "public_COMMENTS_id_activity_fkey" FOREIGN KEY ("id_activity") REFERENCES "public"."ACTIVITIES"("id");

ALTER TABLE ONLY "public"."COMMENTS"
    ADD CONSTRAINT "public_COMMENTS_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."DONATIONS"
    ADD CONSTRAINT "public_DONATIONS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."EVENTS"
    ADD CONSTRAINT "public_EVENTS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "public_MESSAGES_id_receiver_fkey" FOREIGN KEY ("id_receiver") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."MESSAGES"
    ADD CONSTRAINT "public_MESSAGES_id_sender_fkey" FOREIGN KEY ("id_sender") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."NEWS"
    ADD CONSTRAINT "public_NEWS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POLLS_ANSWERS"
    ADD CONSTRAINT "public_POLLS_ANSWERS_id_poll_fkey" FOREIGN KEY ("id_poll") REFERENCES "public"."POLLS"("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "public_POSTS_LIKES_id_post_fkey" FOREIGN KEY ("id_post") REFERENCES "public"."POSTS"("id");

ALTER TABLE ONLY "public"."POSTS_REACTIONS"
    ADD CONSTRAINT "public_POSTS_LIKES_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."POSTS"
    ADD CONSTRAINT "public_POSTS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "public_PRODUCTS_id_buyer_fkey" FOREIGN KEY ("id_buyer") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PRODUCTS"
    ADD CONSTRAINT "public_PRODUCTS_id_user_fkey" FOREIGN KEY ("id_seller") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."PROPOSALS"
    ADD CONSTRAINT "public_PROPOSALS_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."USERS"("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "public_USERS_id_role_fkey" FOREIGN KEY ("id_role") REFERENCES "public"."ROLES"("id");

ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "users_id_referer_fkey" FOREIGN KEY ("id_referer") REFERENCES "public"."USERS"("id");

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES_CATEGORIES" TO "service_role";

GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "anon";
GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "authenticated";
GRANT ALL ON TABLE "public"."ACTIVITIES_USERS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ACTIVITIES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."APPLICATIONS" TO "anon";
GRANT ALL ON TABLE "public"."APPLICATIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."APPLICATIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."APPLICATIONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."CATEGORIES" TO "anon";
GRANT ALL ON TABLE "public"."CATEGORIES" TO "authenticated";
GRANT ALL ON TABLE "public"."CATEGORIES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CATEGORIES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."COMMENTS" TO "anon";
GRANT ALL ON TABLE "public"."COMMENTS" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENTS" TO "service_role";

GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "anon";
GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENTS_REACTIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."COMMENTS_LIKES_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENTS_LIKES_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENTS_LIKES_id_user_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."DONATIONS" TO "anon";
GRANT ALL ON TABLE "public"."DONATIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."DONATIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DONATIONS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."EVENTS" TO "anon";
GRANT ALL ON TABLE "public"."EVENTS" TO "authenticated";
GRANT ALL ON TABLE "public"."EVENTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."EVENTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."MESSAGES" TO "anon";
GRANT ALL ON TABLE "public"."MESSAGES" TO "authenticated";
GRANT ALL ON TABLE "public"."MESSAGES" TO "service_role";

GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MESSAGES_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."NEWS" TO "anon";
GRANT ALL ON TABLE "public"."NEWS" TO "authenticated";
GRANT ALL ON TABLE "public"."NEWS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."NEWS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POLLS" TO "anon";
GRANT ALL ON TABLE "public"."POLLS" TO "authenticated";
GRANT ALL ON TABLE "public"."POLLS" TO "service_role";

GRANT ALL ON TABLE "public"."POLLS_ANSWERS" TO "anon";
GRANT ALL ON TABLE "public"."POLLS_ANSWERS" TO "authenticated";
GRANT ALL ON TABLE "public"."POLLS_ANSWERS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POLLS_ANSWERS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POLLS_ANSWERS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POLLS_ANSWERS_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POLLS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS" TO "anon";
GRANT ALL ON TABLE "public"."POSTS" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS" TO "service_role";

GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "anon";
GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."POSTS_REACTIONS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_LIKES_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_LIKES_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_LIKES_id_user_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."POSTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."PRODUCTS" TO "anon";
GRANT ALL ON TABLE "public"."PRODUCTS" TO "authenticated";
GRANT ALL ON TABLE "public"."PRODUCTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PRODUCTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."PROPOSALS" TO "anon";
GRANT ALL ON TABLE "public"."PROPOSALS" TO "authenticated";
GRANT ALL ON TABLE "public"."PROPOSALS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PROPOSALS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."ROLES" TO "anon";
GRANT ALL ON TABLE "public"."ROLES" TO "authenticated";
GRANT ALL ON TABLE "public"."ROLES" TO "service_role";

GRANT ALL ON TABLE "public"."SPORTS" TO "anon";
GRANT ALL ON TABLE "public"."SPORTS" TO "authenticated";
GRANT ALL ON TABLE "public"."SPORTS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SPORTS_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."USERS" TO "anon";
GRANT ALL ON TABLE "public"."USERS" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS" TO "service_role";

GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."USERS_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
