create table "public"."FOLDERS" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "parent" integer,
    "creator" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "isAdmin" boolean not null default false
);

alter table "public"."DOCUMENTS" add column "folder" bigint;

alter table "public"."DOCUMENTS" add column "assembly" bigint;

alter table "public"."DOCUMENTS" alter column "description" set not null;

alter table "public"."DOCUMENTS" add constraint "public_DOCUMENTS_assembly_fkey" FOREIGN KEY (assembly) REFERENCES "ASSEMBLIES"(id) not valid;

alter table "public"."DOCUMENTS" validate constraint "public_DOCUMENTS_assembly_fkey";

CREATE UNIQUE INDEX "FOLDERS_pkey" ON public."FOLDERS" USING btree (id);

alter table "public"."FOLDERS" add constraint "FOLDERS_pkey" PRIMARY KEY using index "FOLDERS_pkey";

alter table "public"."DOCUMENTS" add constraint "public_DOCUMENTS_folder_fkey" FOREIGN KEY (folder) REFERENCES "FOLDERS"(id) ON DELETE SET NULL not valid;

alter table "public"."DOCUMENTS" validate constraint "public_DOCUMENTS_folder_fkey";

alter table "public"."FOLDERS" add constraint "public_FOLDERS_creator_fkey" FOREIGN KEY (creator) REFERENCES "USERS"(id) not valid;

alter table "public"."FOLDERS" validate constraint "public_FOLDERS_creator_fkey";

alter table "public"."FOLDERS" add constraint "public_FOLDERS_parent_fkey" FOREIGN KEY (parent) REFERENCES "FOLDERS"(id) ON DELETE CASCADE not valid;

alter table "public"."FOLDERS" validate constraint "public_FOLDERS_parent_fkey";

grant delete on table "public"."FOLDERS" to "anon";

grant insert on table "public"."FOLDERS" to "anon";

grant references on table "public"."FOLDERS" to "anon";

grant select on table "public"."FOLDERS" to "anon";

grant trigger on table "public"."FOLDERS" to "anon";

grant truncate on table "public"."FOLDERS" to "anon";

grant update on table "public"."FOLDERS" to "anon";

grant delete on table "public"."FOLDERS" to "authenticated";

grant insert on table "public"."FOLDERS" to "authenticated";

grant references on table "public"."FOLDERS" to "authenticated";

grant select on table "public"."FOLDERS" to "authenticated";

grant trigger on table "public"."FOLDERS" to "authenticated";

grant truncate on table "public"."FOLDERS" to "authenticated";

grant update on table "public"."FOLDERS" to "authenticated";

grant delete on table "public"."FOLDERS" to "service_role";

grant insert on table "public"."FOLDERS" to "service_role";

grant references on table "public"."FOLDERS" to "service_role";

grant select on table "public"."FOLDERS" to "service_role";

grant trigger on table "public"."FOLDERS" to "service_role";

grant truncate on table "public"."FOLDERS" to "service_role";

grant update on table "public"."FOLDERS" to "service_role";
