create type "public"."priority" as enum ('P0', 'P1', 'P2', 'P3');

create type "public"."status" as enum ('not started', 'in progress', 'completed');

create table "public"."ACTIVITIES_TASKS" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "priority" priority not null,
    "id_activity" bigint not null,
    "description" text,
    "title" text not null,
    "status" status not null,
    "id_employee" integer not null
);


CREATE UNIQUE INDEX "ACTIVITIES_TASKS_pkey" ON public."ACTIVITIES_TASKS" USING btree (id);

alter table "public"."ACTIVITIES_TASKS" add constraint "ACTIVITIES_TASKS_pkey" PRIMARY KEY using index "ACTIVITIES_TASKS_pkey";

alter table "public"."ACTIVITIES_TASKS" add constraint "ACTIVITIES_TASKS_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES_EXCEPTIONS"(id) not valid;

alter table "public"."ACTIVITIES_TASKS" validate constraint "ACTIVITIES_TASKS_id_activity_fkey";

alter table "public"."ACTIVITIES_TASKS" add constraint "ACTIVITIES_TASKS_id_employee_fkey" FOREIGN KEY (id_employee) REFERENCES "USERS"(id) not valid;

alter table "public"."ACTIVITIES_TASKS" validate constraint "ACTIVITIES_TASKS_id_employee_fkey";

grant delete on table "public"."ACTIVITIES_TASKS" to "anon";

grant insert on table "public"."ACTIVITIES_TASKS" to "anon";

grant references on table "public"."ACTIVITIES_TASKS" to "anon";

grant select on table "public"."ACTIVITIES_TASKS" to "anon";

grant trigger on table "public"."ACTIVITIES_TASKS" to "anon";

grant truncate on table "public"."ACTIVITIES_TASKS" to "anon";

grant update on table "public"."ACTIVITIES_TASKS" to "anon";

grant delete on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant insert on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant references on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant select on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant trigger on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant truncate on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant update on table "public"."ACTIVITIES_TASKS" to "authenticated";

grant delete on table "public"."ACTIVITIES_TASKS" to "service_role";

grant insert on table "public"."ACTIVITIES_TASKS" to "service_role";

grant references on table "public"."ACTIVITIES_TASKS" to "service_role";

grant select on table "public"."ACTIVITIES_TASKS" to "service_role";

grant trigger on table "public"."ACTIVITIES_TASKS" to "service_role";

grant truncate on table "public"."ACTIVITIES_TASKS" to "service_role";

grant update on table "public"."ACTIVITIES_TASKS" to "service_role";

alter table "public"."ACTIVITIES_TASKS" alter column "id_employee" drop not null;

alter table "public"."ACTIVITIES_TASKS" drop constraint "ACTIVITIES_TASKS_id_activity_fkey";

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "new_end_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "new_start_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "old_end_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "old_start_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" add column "end_date" timestamp without time zone;

alter table "public"."ACTIVITIES_EXCEPTIONS" add column "start_date" timestamp without time zone;

alter table "public"."ACTIVITIES_TASKS" drop column "id_activity";

alter table "public"."ACTIVITIES_TASKS" add column "id_activity_exception" bigint not null;

alter table "public"."ACTIVITIES_TASKS" add constraint "ACTIVITIES_TASKS_id_activity_fkey" FOREIGN KEY (id_activity_exception) REFERENCES "ACTIVITIES_EXCEPTIONS"(id) not valid;

alter table "public"."ACTIVITIES_TASKS" validate constraint "ACTIVITIES_TASKS_id_activity_fkey";

alter table "public"."ACTIVITIES_EXCEPTIONS" alter column "end_date" set not null;

alter table "public"."ACTIVITIES_EXCEPTIONS" alter column "start_date" set not null;

alter table "public"."ACTIVITIES_EXCEPTIONS" alter column "id_activity" set not null;

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "end_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" drop column "start_date";

alter table "public"."ACTIVITIES_EXCEPTIONS" add column "date" date not null;

alter table "public"."ACTIVITIES_TASKS" add column "id_activity" bigint;

alter table "public"."ACTIVITIES_TASKS" add constraint "ACTIVITIES_TASKS_id_activity_fkey1" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) not valid;

alter table "public"."ACTIVITIES_TASKS" validate constraint "ACTIVITIES_TASKS_id_activity_fkey1";
