revoke delete on table "public"."POST_CATEGORIES" from "anon";

revoke insert on table "public"."POST_CATEGORIES" from "anon";

revoke references on table "public"."POST_CATEGORIES" from "anon";

revoke select on table "public"."POST_CATEGORIES" from "anon";

revoke trigger on table "public"."POST_CATEGORIES" from "anon";

revoke truncate on table "public"."POST_CATEGORIES" from "anon";

revoke update on table "public"."POST_CATEGORIES" from "anon";

revoke delete on table "public"."POST_CATEGORIES" from "authenticated";

revoke insert on table "public"."POST_CATEGORIES" from "authenticated";

revoke references on table "public"."POST_CATEGORIES" from "authenticated";

revoke select on table "public"."POST_CATEGORIES" from "authenticated";

revoke trigger on table "public"."POST_CATEGORIES" from "authenticated";

revoke truncate on table "public"."POST_CATEGORIES" from "authenticated";

revoke update on table "public"."POST_CATEGORIES" from "authenticated";

revoke delete on table "public"."POST_CATEGORIES" from "service_role";

revoke insert on table "public"."POST_CATEGORIES" from "service_role";

revoke references on table "public"."POST_CATEGORIES" from "service_role";

revoke select on table "public"."POST_CATEGORIES" from "service_role";

revoke trigger on table "public"."POST_CATEGORIES" from "service_role";

revoke truncate on table "public"."POST_CATEGORIES" from "service_role";

revoke update on table "public"."POST_CATEGORIES" from "service_role";

alter table "public"."POST_CATEGORIES" drop constraint "public_POST_CATEGORIES_category_id_fkey";

alter table "public"."POST_CATEGORIES" drop constraint "public_POST_CATEGORIES_post_id_fkey";

alter table "public"."POST_CATEGORIES" drop constraint "POST_CATEGORIES_pkey";

drop index if exists "public"."POST_CATEGORIES_pkey";

drop table "public"."POST_CATEGORIES";

create table "public"."POSTS_CATEGORIES" (
    "id_post" integer not null,
    "id_category" bigint not null,
    "id" integer generated by default as identity not null
);


create table "public"."POSTS_VIEWS" (
    "viewed_at" timestamp with time zone not null default now(),
    "id_user" integer not null,
    "id_post" integer not null
);


CREATE UNIQUE INDEX "POSTS_CATEGORIES_id_key" ON public."POSTS_CATEGORIES" USING btree (id);

CREATE UNIQUE INDEX "POSTS_CATEGORIES_pkey" ON public."POSTS_CATEGORIES" USING btree (id);

CREATE UNIQUE INDEX "POSTS_VIEWS_pkey" ON public."POSTS_VIEWS" USING btree (id_user, id_post);

alter table "public"."POSTS_CATEGORIES" add constraint "POSTS_CATEGORIES_pkey" PRIMARY KEY using index "POSTS_CATEGORIES_pkey";

alter table "public"."POSTS_VIEWS" add constraint "POSTS_VIEWS_pkey" PRIMARY KEY using index "POSTS_VIEWS_pkey";

alter table "public"."POSTS_CATEGORIES" add constraint "POSTS_CATEGORIES_id_key" UNIQUE using index "POSTS_CATEGORIES_id_key";

alter table "public"."POSTS_CATEGORIES" add constraint "public_POST_CATEGORIES_category_id_fkey" FOREIGN KEY (id_category) REFERENCES "CATEGORIES"(id) not valid;

alter table "public"."POSTS_CATEGORIES" validate constraint "public_POST_CATEGORIES_category_id_fkey";

alter table "public"."POSTS_CATEGORIES" add constraint "public_POST_CATEGORIES_post_id_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."POSTS_CATEGORIES" validate constraint "public_POST_CATEGORIES_post_id_fkey";

alter table "public"."POSTS_VIEWS" add constraint "public_POSTS_VIEWS_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."POSTS_VIEWS" validate constraint "public_POSTS_VIEWS_id_post_fkey";

alter table "public"."POSTS_VIEWS" add constraint "public_POSTS_VIEWS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."POSTS_VIEWS" validate constraint "public_POSTS_VIEWS_id_user_fkey";

grant delete on table "public"."POSTS_CATEGORIES" to "anon";

grant insert on table "public"."POSTS_CATEGORIES" to "anon";

grant references on table "public"."POSTS_CATEGORIES" to "anon";

grant select on table "public"."POSTS_CATEGORIES" to "anon";

grant trigger on table "public"."POSTS_CATEGORIES" to "anon";

grant truncate on table "public"."POSTS_CATEGORIES" to "anon";

grant update on table "public"."POSTS_CATEGORIES" to "anon";

grant delete on table "public"."POSTS_CATEGORIES" to "authenticated";

grant insert on table "public"."POSTS_CATEGORIES" to "authenticated";

grant references on table "public"."POSTS_CATEGORIES" to "authenticated";

grant select on table "public"."POSTS_CATEGORIES" to "authenticated";

grant trigger on table "public"."POSTS_CATEGORIES" to "authenticated";

grant truncate on table "public"."POSTS_CATEGORIES" to "authenticated";

grant update on table "public"."POSTS_CATEGORIES" to "authenticated";

grant delete on table "public"."POSTS_CATEGORIES" to "service_role";

grant insert on table "public"."POSTS_CATEGORIES" to "service_role";

grant references on table "public"."POSTS_CATEGORIES" to "service_role";

grant select on table "public"."POSTS_CATEGORIES" to "service_role";

grant trigger on table "public"."POSTS_CATEGORIES" to "service_role";

grant truncate on table "public"."POSTS_CATEGORIES" to "service_role";

grant update on table "public"."POSTS_CATEGORIES" to "service_role";

grant delete on table "public"."POSTS_VIEWS" to "anon";

grant insert on table "public"."POSTS_VIEWS" to "anon";

grant references on table "public"."POSTS_VIEWS" to "anon";

grant select on table "public"."POSTS_VIEWS" to "anon";

grant trigger on table "public"."POSTS_VIEWS" to "anon";

grant truncate on table "public"."POSTS_VIEWS" to "anon";

grant update on table "public"."POSTS_VIEWS" to "anon";

grant delete on table "public"."POSTS_VIEWS" to "authenticated";

grant insert on table "public"."POSTS_VIEWS" to "authenticated";

grant references on table "public"."POSTS_VIEWS" to "authenticated";

grant select on table "public"."POSTS_VIEWS" to "authenticated";

grant trigger on table "public"."POSTS_VIEWS" to "authenticated";

grant truncate on table "public"."POSTS_VIEWS" to "authenticated";

grant update on table "public"."POSTS_VIEWS" to "authenticated";

grant delete on table "public"."POSTS_VIEWS" to "service_role";

grant insert on table "public"."POSTS_VIEWS" to "service_role";

grant references on table "public"."POSTS_VIEWS" to "service_role";

grant select on table "public"."POSTS_VIEWS" to "service_role";

grant trigger on table "public"."POSTS_VIEWS" to "service_role";

grant truncate on table "public"."POSTS_VIEWS" to "service_role";

grant update on table "public"."POSTS_VIEWS" to "service_role";


