create extension if not exists "isn" with schema "extensions";


create table "public"."ACTIVITIES" (
    "id" bigint generated by default as identity not null,
    "max_participants" integer not null,
    "name" text not null,
    "duration_minute" bigint not null,
    "id_sport" bigint
);


create table "public"."ACTIVITIES_CATEGORIES" (
    "id_activity" bigint not null,
    "id_category" bigint not null
);


create table "public"."ACTIVITIES_USERS" (
    "id_activity" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "id_user" integer not null
);


create table "public"."ADDRESSES" (
    "id" bigint generated by default as identity not null,
    "road" text not null,
    "postal_code" text not null,
    "complement" text,
    "city" text not null,
    "number" integer not null,
    "name" text,
    "id_lease" bigint
);


create table "public"."ADDRESSES_MATERIALS" (
    "quantity" integer not null,
    "id_material" bigint not null,
    "id_address" bigint not null
);


create table "public"."APPLICATIONS" (
    "id" bigint generated by default as identity not null,
    "nature" text not null,
    "reason" text not null,
    "reply" integer not null default 0,
    "id_user" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


create table "public"."CATEGORIES" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "public"."COMMENTS" (
    "id" integer generated by default as identity not null,
    "content" text not null,
    "id_response" integer,
    "id_post" integer,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "id_activity" bigint,
    "id_user" integer not null
);


create table "public"."COMMENTS_REACTIONS" (
    "id_user" integer generated by default as identity not null,
    "id_comment" integer not null,
    "reaction" text,
    "like" boolean
);


create table "public"."DONATIONS" (
    "id" bigint generated by default as identity not null,
    "money" bigint,
    "id_user" integer not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."EVENTS" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "id_user" integer not null
);


create table "public"."LANDLORD" (
    "id" bigint generated by default as identity not null,
    "first_name" text not null,
    "last_name" text not null,
    "email" text not null,
    "phone" text not null
);


create table "public"."LEASE" (
    "id" bigint generated by default as identity not null,
    "rent" integer not null,
    "payment_date" timestamp with time zone not null,
    "start_lease" timestamp with time zone not null,
    "end_lease" timestamp with time zone not null,
    "id_landlord" bigint not null
);


create table "public"."MATCHES" (
    "id" bigint generated by default as identity not null,
    "end_time" timestamp with time zone,
    "start_time" timestamp with time zone
);


create table "public"."MATERIALS" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "public"."MESSAGES" (
    "id" bigint generated by default as identity not null,
    "mesage" text,
    "id_sender" integer not null,
    "id_receiver" integer not null,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."NEWS" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "content" text not null,
    "id_user" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


create table "public"."POLLS" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "content" text
);


create table "public"."POLLS_ANSWERS" (
    "id" bigint generated by default as identity not null,
    "answer" text not null,
    "id_poll" bigint not null
);


create table "public"."POSTS" (
    "id" integer generated by default as identity not null,
    "content" text not null,
    "title" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "id_user" integer not null
);


create table "public"."POSTS_REACTIONS" (
    "id_user" integer generated by default as identity not null,
    "id_post" integer not null,
    "reaction" text,
    "like" boolean
);


create table "public"."PRODUCTS" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null,
    "price" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "id_seller" integer not null,
    "id_buyer" integer
);


create table "public"."PROPOSALS" (
    "id" bigint generated by default as identity not null,
    "proposal" text not null,
    "id_user" integer not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."RESERVED" (
    "created_at" timestamp with time zone not null default now(),
    "quantity" integer not null,
    "date_reserved" date not null,
    "id_material" bigint,
    "id_activity" bigint,
    "id_tournament" bigint,
    "id" bigint generated by default as identity not null
);


create table "public"."ROLES" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


create table "public"."SPORTS" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


create table "public"."TEAMS" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "id_tournament" bigint not null
);


create table "public"."TEAMS_MATCHES" (
    "winner" boolean,
    "id_team" bigint not null,
    "id_match" bigint not null
);


create table "public"."TOURNAMENTS" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "default_match_length" integer,
    "name" text not null,
    "max_participants" integer not null,
    "team_capacity" integer not null,
    "rules" text,
    "prize" text,
    "id_address" bigint
);


create table "public"."TOURNAMENTS_MATCHES" (
    "id_match" bigint not null,
    "id_tournament" bigint not null,
    "round" integer not null
);


create table "public"."USERS" (
    "id" integer generated by default as identity not null,
    "email" character varying(255) not null,
    "username" text not null,
    "first_name" text not null,
    "last_name" text not null,
    "id_referer" integer,
    "id_auth" uuid,
    "date_validity" timestamp with time zone
);


create table "public"."USERS_ROLES" (
    "id_user" integer not null,
    "id_role" integer not null
);


create table "public"."USERS_TEAMS" (
    "information" text,
    "position" text,
    "id_user" integer not null,
    "id_team" bigint not null
);


CREATE UNIQUE INDEX "ACTIVITIES_CATEGORIES_pkey" ON public."ACTIVITIES_CATEGORIES" USING btree (id_activity, id_category);

CREATE UNIQUE INDEX "ACTIVITIES_USERS_pkey" ON public."ACTIVITIES_USERS" USING btree (id_activity, id_user);

CREATE UNIQUE INDEX "ACTIVITIES_pkey" ON public."ACTIVITIES" USING btree (id);

CREATE UNIQUE INDEX "ADDRESSES_MATERIALS_pkey" ON public."ADDRESSES_MATERIALS" USING btree (id_material, id_address);

CREATE UNIQUE INDEX "ADDRESS_pkey" ON public."ADDRESSES" USING btree (id);

CREATE UNIQUE INDEX "APPLICATIONS_pkey" ON public."APPLICATIONS" USING btree (id);

CREATE UNIQUE INDEX "CATEGORIES_name_key" ON public."CATEGORIES" USING btree (name);

CREATE UNIQUE INDEX "CATEGORIES_pkey" ON public."CATEGORIES" USING btree (id);

CREATE UNIQUE INDEX "COMMENTS_REACTIONS_pkey" ON public."COMMENTS_REACTIONS" USING btree (id_user, id_comment);

CREATE UNIQUE INDEX "DONATIONS_pkey" ON public."DONATIONS" USING btree (id);

CREATE UNIQUE INDEX "EVENTS_pkey" ON public."EVENTS" USING btree (id);

CREATE UNIQUE INDEX "LANDLORD_pkey" ON public."LANDLORD" USING btree (id);

CREATE UNIQUE INDEX "LEASE_pkey" ON public."LEASE" USING btree (id);

CREATE UNIQUE INDEX "MATCHES_pkey" ON public."MATCHES" USING btree (id);

CREATE UNIQUE INDEX "MATERIALS_pkey" ON public."MATERIALS" USING btree (id);

CREATE UNIQUE INDEX "MESSAGES_pkey" ON public."MESSAGES" USING btree (id);

CREATE UNIQUE INDEX "NEWS_pkey" ON public."NEWS" USING btree (id);

CREATE UNIQUE INDEX "POLLS_ANSWERS_pkey" ON public."POLLS_ANSWERS" USING btree (id);

CREATE UNIQUE INDEX "POLLS_pkey" ON public."POLLS" USING btree (id);

CREATE UNIQUE INDEX "POSTS_LIKES_pkey" ON public."POSTS_REACTIONS" USING btree (id_user, id_post);

CREATE INDEX "POSTS_id_idx" ON public."POSTS" USING btree (id);

CREATE UNIQUE INDEX "PRODUCTS_pkey" ON public."PRODUCTS" USING btree (id);

CREATE UNIQUE INDEX "PROPOSALS_pkey" ON public."PROPOSALS" USING btree (id);

CREATE UNIQUE INDEX "RESERVED_pkey" ON public."RESERVED" USING btree (id);

CREATE UNIQUE INDEX "SPORTS_name_key" ON public."SPORTS" USING btree (name);

CREATE UNIQUE INDEX "SPORTS_pkey" ON public."SPORTS" USING btree (id);

CREATE UNIQUE INDEX "TEAMS_MATCHES_pkey" ON public."TEAMS_MATCHES" USING btree (id_team, id_match);

CREATE UNIQUE INDEX "TEAMS_pkey" ON public."TEAMS" USING btree (id);

CREATE UNIQUE INDEX "TOURNAMENTS_MATCHES_pkey" ON public."TOURNAMENTS_MATCHES" USING btree (id_match, id_tournament);

CREATE UNIQUE INDEX "TOURNAMENTS_pkey" ON public."TOURNAMENTS" USING btree (id);

CREATE UNIQUE INDEX "USERS_ROLES_pkey" ON public."USERS_ROLES" USING btree (id_user, id_role);

CREATE UNIQUE INDEX "USERS_TEAMS_pkey" ON public."USERS_TEAMS" USING btree (id_user, id_team);

CREATE UNIQUE INDEX "USERS_id_auth_key" ON public."USERS" USING btree (id_auth);

CREATE UNIQUE INDEX comments_pkey ON public."COMMENTS" USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON public."POSTS" USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public."ROLES" USING btree (id);

CREATE UNIQUE INDEX users_email_key ON public."USERS" USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public."USERS" USING btree (id);

alter table "public"."ACTIVITIES" add constraint "ACTIVITIES_pkey" PRIMARY KEY using index "ACTIVITIES_pkey";

alter table "public"."ACTIVITIES_CATEGORIES" add constraint "ACTIVITIES_CATEGORIES_pkey" PRIMARY KEY using index "ACTIVITIES_CATEGORIES_pkey";

alter table "public"."ACTIVITIES_USERS" add constraint "ACTIVITIES_USERS_pkey" PRIMARY KEY using index "ACTIVITIES_USERS_pkey";

alter table "public"."ADDRESSES" add constraint "ADDRESS_pkey" PRIMARY KEY using index "ADDRESS_pkey";

alter table "public"."ADDRESSES_MATERIALS" add constraint "ADDRESSES_MATERIALS_pkey" PRIMARY KEY using index "ADDRESSES_MATERIALS_pkey";

alter table "public"."APPLICATIONS" add constraint "APPLICATIONS_pkey" PRIMARY KEY using index "APPLICATIONS_pkey";

alter table "public"."CATEGORIES" add constraint "CATEGORIES_pkey" PRIMARY KEY using index "CATEGORIES_pkey";

alter table "public"."COMMENTS" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."COMMENTS_REACTIONS" add constraint "COMMENTS_REACTIONS_pkey" PRIMARY KEY using index "COMMENTS_REACTIONS_pkey";

alter table "public"."DONATIONS" add constraint "DONATIONS_pkey" PRIMARY KEY using index "DONATIONS_pkey";

alter table "public"."EVENTS" add constraint "EVENTS_pkey" PRIMARY KEY using index "EVENTS_pkey";

alter table "public"."LANDLORD" add constraint "LANDLORD_pkey" PRIMARY KEY using index "LANDLORD_pkey";

alter table "public"."LEASE" add constraint "LEASE_pkey" PRIMARY KEY using index "LEASE_pkey";

alter table "public"."MATCHES" add constraint "MATCHES_pkey" PRIMARY KEY using index "MATCHES_pkey";

alter table "public"."MATERIALS" add constraint "MATERIALS_pkey" PRIMARY KEY using index "MATERIALS_pkey";

alter table "public"."MESSAGES" add constraint "MESSAGES_pkey" PRIMARY KEY using index "MESSAGES_pkey";

alter table "public"."NEWS" add constraint "NEWS_pkey" PRIMARY KEY using index "NEWS_pkey";

alter table "public"."POLLS" add constraint "POLLS_pkey" PRIMARY KEY using index "POLLS_pkey";

alter table "public"."POLLS_ANSWERS" add constraint "POLLS_ANSWERS_pkey" PRIMARY KEY using index "POLLS_ANSWERS_pkey";

alter table "public"."POSTS" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."POSTS_REACTIONS" add constraint "POSTS_LIKES_pkey" PRIMARY KEY using index "POSTS_LIKES_pkey";

alter table "public"."PRODUCTS" add constraint "PRODUCTS_pkey" PRIMARY KEY using index "PRODUCTS_pkey";

alter table "public"."PROPOSALS" add constraint "PROPOSALS_pkey" PRIMARY KEY using index "PROPOSALS_pkey";

alter table "public"."RESERVED" add constraint "RESERVED_pkey" PRIMARY KEY using index "RESERVED_pkey";

alter table "public"."ROLES" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."SPORTS" add constraint "SPORTS_pkey" PRIMARY KEY using index "SPORTS_pkey";

alter table "public"."TEAMS" add constraint "TEAMS_pkey" PRIMARY KEY using index "TEAMS_pkey";

alter table "public"."TEAMS_MATCHES" add constraint "TEAMS_MATCHES_pkey" PRIMARY KEY using index "TEAMS_MATCHES_pkey";

alter table "public"."TOURNAMENTS" add constraint "TOURNAMENTS_pkey" PRIMARY KEY using index "TOURNAMENTS_pkey";

alter table "public"."TOURNAMENTS_MATCHES" add constraint "TOURNAMENTS_MATCHES_pkey" PRIMARY KEY using index "TOURNAMENTS_MATCHES_pkey";

alter table "public"."USERS" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."USERS_ROLES" add constraint "USERS_ROLES_pkey" PRIMARY KEY using index "USERS_ROLES_pkey";

alter table "public"."USERS_TEAMS" add constraint "USERS_TEAMS_pkey" PRIMARY KEY using index "USERS_TEAMS_pkey";

alter table "public"."ACTIVITIES" add constraint "public_ACTIVITIES_id_sport_fkey" FOREIGN KEY (id_sport) REFERENCES "SPORTS"(id) not valid;

alter table "public"."ACTIVITIES" validate constraint "public_ACTIVITIES_id_sport_fkey";

alter table "public"."ACTIVITIES_CATEGORIES" add constraint "public_ACTIVITIES_CATEGORIES_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) not valid;

alter table "public"."ACTIVITIES_CATEGORIES" validate constraint "public_ACTIVITIES_CATEGORIES_id_activity_fkey";

alter table "public"."ACTIVITIES_CATEGORIES" add constraint "public_ACTIVITIES_CATEGORIES_id_category_fkey" FOREIGN KEY (id_category) REFERENCES "CATEGORIES"(id) not valid;

alter table "public"."ACTIVITIES_CATEGORIES" validate constraint "public_ACTIVITIES_CATEGORIES_id_category_fkey";

alter table "public"."ACTIVITIES_USERS" add constraint "public_ACTIVITIES_USERS_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) not valid;

alter table "public"."ACTIVITIES_USERS" validate constraint "public_ACTIVITIES_USERS_id_activity_fkey";

alter table "public"."ACTIVITIES_USERS" add constraint "public_ACTIVITIES_USERS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."ACTIVITIES_USERS" validate constraint "public_ACTIVITIES_USERS_id_user_fkey";

alter table "public"."ADDRESSES" add constraint "public_ADDRESS_id_lease_fkey" FOREIGN KEY (id_lease) REFERENCES "LEASE"(id) not valid;

alter table "public"."ADDRESSES" validate constraint "public_ADDRESS_id_lease_fkey";

alter table "public"."ADDRESSES_MATERIALS" add constraint "public_ADDRESSES_MATERIALS_id_address_fkey" FOREIGN KEY (id_address) REFERENCES "ADDRESSES"(id) not valid;

alter table "public"."ADDRESSES_MATERIALS" validate constraint "public_ADDRESSES_MATERIALS_id_address_fkey";

alter table "public"."ADDRESSES_MATERIALS" add constraint "public_ADDRESSES_MATERIALS_id_material_fkey" FOREIGN KEY (id_material) REFERENCES "MATERIALS"(id) not valid;

alter table "public"."ADDRESSES_MATERIALS" validate constraint "public_ADDRESSES_MATERIALS_id_material_fkey";

alter table "public"."APPLICATIONS" add constraint "public_APPLICATIONS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."APPLICATIONS" validate constraint "public_APPLICATIONS_id_user_fkey";

alter table "public"."CATEGORIES" add constraint "CATEGORIES_name_key" UNIQUE using index "CATEGORIES_name_key";

alter table "public"."COMMENTS" add constraint "comments_id_comment_fkey" FOREIGN KEY (id_response) REFERENCES "COMMENTS"(id) not valid;

alter table "public"."COMMENTS" validate constraint "comments_id_comment_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_activity_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_post_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_user_fkey";

alter table "public"."COMMENTS_REACTIONS" add constraint "public_COMMENTS_LIKES_id_comment_fkey" FOREIGN KEY (id_comment) REFERENCES "COMMENTS"(id) not valid;

alter table "public"."COMMENTS_REACTIONS" validate constraint "public_COMMENTS_LIKES_id_comment_fkey";

alter table "public"."COMMENTS_REACTIONS" add constraint "public_COMMENTS_LIKES_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."COMMENTS_REACTIONS" validate constraint "public_COMMENTS_LIKES_id_user_fkey";

alter table "public"."DONATIONS" add constraint "public_DONATIONS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."DONATIONS" validate constraint "public_DONATIONS_id_user_fkey";

alter table "public"."EVENTS" add constraint "public_EVENTS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."EVENTS" validate constraint "public_EVENTS_id_user_fkey";

alter table "public"."LEASE" add constraint "public_LEASE_id_landlord_fkey" FOREIGN KEY (id_landlord) REFERENCES "LANDLORD"(id) not valid;

alter table "public"."LEASE" validate constraint "public_LEASE_id_landlord_fkey";

alter table "public"."MESSAGES" add constraint "public_MESSAGES_id_receiver_fkey" FOREIGN KEY (id_receiver) REFERENCES "USERS"(id) not valid;

alter table "public"."MESSAGES" validate constraint "public_MESSAGES_id_receiver_fkey";

alter table "public"."MESSAGES" add constraint "public_MESSAGES_id_sender_fkey" FOREIGN KEY (id_sender) REFERENCES "USERS"(id) not valid;

alter table "public"."MESSAGES" validate constraint "public_MESSAGES_id_sender_fkey";

alter table "public"."NEWS" add constraint "public_NEWS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."NEWS" validate constraint "public_NEWS_id_user_fkey";

alter table "public"."POLLS_ANSWERS" add constraint "public_POLLS_ANSWERS_id_poll_fkey" FOREIGN KEY (id_poll) REFERENCES "POLLS"(id) not valid;

alter table "public"."POLLS_ANSWERS" validate constraint "public_POLLS_ANSWERS_id_poll_fkey";

alter table "public"."POSTS" add constraint "public_POSTS_user_id_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."POSTS" validate constraint "public_POSTS_user_id_fkey";

alter table "public"."POSTS_REACTIONS" add constraint "public_POSTS_LIKES_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."POSTS_REACTIONS" validate constraint "public_POSTS_LIKES_id_post_fkey";

alter table "public"."POSTS_REACTIONS" add constraint "public_POSTS_LIKES_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."POSTS_REACTIONS" validate constraint "public_POSTS_LIKES_id_user_fkey";

alter table "public"."PRODUCTS" add constraint "public_PRODUCTS_id_buyer_fkey" FOREIGN KEY (id_buyer) REFERENCES "USERS"(id) not valid;

alter table "public"."PRODUCTS" validate constraint "public_PRODUCTS_id_buyer_fkey";

alter table "public"."PRODUCTS" add constraint "public_PRODUCTS_id_user_fkey" FOREIGN KEY (id_seller) REFERENCES "USERS"(id) not valid;

alter table "public"."PRODUCTS" validate constraint "public_PRODUCTS_id_user_fkey";

alter table "public"."PROPOSALS" add constraint "public_PROPOSALS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."PROPOSALS" validate constraint "public_PROPOSALS_id_user_fkey";

alter table "public"."RESERVED" add constraint "public_RESERVED_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) not valid;

alter table "public"."RESERVED" validate constraint "public_RESERVED_id_activity_fkey";

alter table "public"."RESERVED" add constraint "public_RESERVED_id_material_fkey" FOREIGN KEY (id_material) REFERENCES "MATERIALS"(id) not valid;

alter table "public"."RESERVED" validate constraint "public_RESERVED_id_material_fkey";

alter table "public"."RESERVED" add constraint "public_RESERVED_id_tournament_fkey" FOREIGN KEY (id_tournament) REFERENCES "TOURNAMENTS"(id) not valid;

alter table "public"."RESERVED" validate constraint "public_RESERVED_id_tournament_fkey";

alter table "public"."SPORTS" add constraint "SPORTS_name_key" UNIQUE using index "SPORTS_name_key";

alter table "public"."TEAMS" add constraint "public_TEAMS_id_tournament_fkey" FOREIGN KEY (id_tournament) REFERENCES "TOURNAMENTS"(id) not valid;

alter table "public"."TEAMS" validate constraint "public_TEAMS_id_tournament_fkey";

alter table "public"."TEAMS_MATCHES" add constraint "public_TEAMS_MATCHES_id_match_fkey" FOREIGN KEY (id_match) REFERENCES "MATCHES"(id) not valid;

alter table "public"."TEAMS_MATCHES" validate constraint "public_TEAMS_MATCHES_id_match_fkey";

alter table "public"."TEAMS_MATCHES" add constraint "public_TEAMS_MATCHES_id_team_fkey" FOREIGN KEY (id_team) REFERENCES "TEAMS"(id) not valid;

alter table "public"."TEAMS_MATCHES" validate constraint "public_TEAMS_MATCHES_id_team_fkey";

alter table "public"."TOURNAMENTS" add constraint "public_TOURNAMENTS_id_address_fkey" FOREIGN KEY (id_address) REFERENCES "TOURNAMENTS"(id) not valid;

alter table "public"."TOURNAMENTS" validate constraint "public_TOURNAMENTS_id_address_fkey";

alter table "public"."TOURNAMENTS_MATCHES" add constraint "public_TOURNAMENTS_MATCHES_id_match_fkey" FOREIGN KEY (id_match) REFERENCES "MATCHES"(id) not valid;

alter table "public"."TOURNAMENTS_MATCHES" validate constraint "public_TOURNAMENTS_MATCHES_id_match_fkey";

alter table "public"."TOURNAMENTS_MATCHES" add constraint "public_TOURNAMENTS_MATCHES_id_tournament_fkey" FOREIGN KEY (id_tournament) REFERENCES "TOURNAMENTS"(id) not valid;

alter table "public"."TOURNAMENTS_MATCHES" validate constraint "public_TOURNAMENTS_MATCHES_id_tournament_fkey";

alter table "public"."USERS" add constraint "USERS_id_auth_key" UNIQUE using index "USERS_id_auth_key";

alter table "public"."USERS" add constraint "public_USERS_id_auth_fkey" FOREIGN KEY (id_auth) REFERENCES auth.users(id) not valid;

alter table "public"."USERS" validate constraint "public_USERS_id_auth_fkey";

alter table "public"."USERS" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."USERS" add constraint "users_id_referer_fkey" FOREIGN KEY (id_referer) REFERENCES "USERS"(id) not valid;

alter table "public"."USERS" validate constraint "users_id_referer_fkey";

alter table "public"."USERS_ROLES" add constraint "public_USERS_ROLES_id_role_fkey" FOREIGN KEY (id_role) REFERENCES "ROLES"(id) not valid;

alter table "public"."USERS_ROLES" validate constraint "public_USERS_ROLES_id_role_fkey";

alter table "public"."USERS_ROLES" add constraint "public_USERS_ROLES_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."USERS_ROLES" validate constraint "public_USERS_ROLES_id_user_fkey";

alter table "public"."USERS_TEAMS" add constraint "public_USERS_TEAMS_id_team_fkey" FOREIGN KEY (id_team) REFERENCES "TEAMS"(id) not valid;

alter table "public"."USERS_TEAMS" validate constraint "public_USERS_TEAMS_id_team_fkey";

alter table "public"."USERS_TEAMS" add constraint "public_USERS_TEAMS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."USERS_TEAMS" validate constraint "public_USERS_TEAMS_id_user_fkey";

grant delete on table "public"."ACTIVITIES" to "anon";

grant insert on table "public"."ACTIVITIES" to "anon";

grant references on table "public"."ACTIVITIES" to "anon";

grant select on table "public"."ACTIVITIES" to "anon";

grant trigger on table "public"."ACTIVITIES" to "anon";

grant truncate on table "public"."ACTIVITIES" to "anon";

grant update on table "public"."ACTIVITIES" to "anon";

grant delete on table "public"."ACTIVITIES" to "authenticated";

grant insert on table "public"."ACTIVITIES" to "authenticated";

grant references on table "public"."ACTIVITIES" to "authenticated";

grant select on table "public"."ACTIVITIES" to "authenticated";

grant trigger on table "public"."ACTIVITIES" to "authenticated";

grant truncate on table "public"."ACTIVITIES" to "authenticated";

grant update on table "public"."ACTIVITIES" to "authenticated";

grant delete on table "public"."ACTIVITIES" to "service_role";

grant insert on table "public"."ACTIVITIES" to "service_role";

grant references on table "public"."ACTIVITIES" to "service_role";

grant select on table "public"."ACTIVITIES" to "service_role";

grant trigger on table "public"."ACTIVITIES" to "service_role";

grant truncate on table "public"."ACTIVITIES" to "service_role";

grant update on table "public"."ACTIVITIES" to "service_role";

grant delete on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant insert on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant references on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant select on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant trigger on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant truncate on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant update on table "public"."ACTIVITIES_CATEGORIES" to "anon";

grant delete on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant insert on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant references on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant select on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant trigger on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant truncate on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant update on table "public"."ACTIVITIES_CATEGORIES" to "authenticated";

grant delete on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant insert on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant references on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant select on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant trigger on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant truncate on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant update on table "public"."ACTIVITIES_CATEGORIES" to "service_role";

grant delete on table "public"."ACTIVITIES_USERS" to "anon";

grant insert on table "public"."ACTIVITIES_USERS" to "anon";

grant references on table "public"."ACTIVITIES_USERS" to "anon";

grant select on table "public"."ACTIVITIES_USERS" to "anon";

grant trigger on table "public"."ACTIVITIES_USERS" to "anon";

grant truncate on table "public"."ACTIVITIES_USERS" to "anon";

grant update on table "public"."ACTIVITIES_USERS" to "anon";

grant delete on table "public"."ACTIVITIES_USERS" to "authenticated";

grant insert on table "public"."ACTIVITIES_USERS" to "authenticated";

grant references on table "public"."ACTIVITIES_USERS" to "authenticated";

grant select on table "public"."ACTIVITIES_USERS" to "authenticated";

grant trigger on table "public"."ACTIVITIES_USERS" to "authenticated";

grant truncate on table "public"."ACTIVITIES_USERS" to "authenticated";

grant update on table "public"."ACTIVITIES_USERS" to "authenticated";

grant delete on table "public"."ACTIVITIES_USERS" to "service_role";

grant insert on table "public"."ACTIVITIES_USERS" to "service_role";

grant references on table "public"."ACTIVITIES_USERS" to "service_role";

grant select on table "public"."ACTIVITIES_USERS" to "service_role";

grant trigger on table "public"."ACTIVITIES_USERS" to "service_role";

grant truncate on table "public"."ACTIVITIES_USERS" to "service_role";

grant update on table "public"."ACTIVITIES_USERS" to "service_role";

grant delete on table "public"."ADDRESSES" to "anon";

grant insert on table "public"."ADDRESSES" to "anon";

grant references on table "public"."ADDRESSES" to "anon";

grant select on table "public"."ADDRESSES" to "anon";

grant trigger on table "public"."ADDRESSES" to "anon";

grant truncate on table "public"."ADDRESSES" to "anon";

grant update on table "public"."ADDRESSES" to "anon";

grant delete on table "public"."ADDRESSES" to "authenticated";

grant insert on table "public"."ADDRESSES" to "authenticated";

grant references on table "public"."ADDRESSES" to "authenticated";

grant select on table "public"."ADDRESSES" to "authenticated";

grant trigger on table "public"."ADDRESSES" to "authenticated";

grant truncate on table "public"."ADDRESSES" to "authenticated";

grant update on table "public"."ADDRESSES" to "authenticated";

grant delete on table "public"."ADDRESSES" to "service_role";

grant insert on table "public"."ADDRESSES" to "service_role";

grant references on table "public"."ADDRESSES" to "service_role";

grant select on table "public"."ADDRESSES" to "service_role";

grant trigger on table "public"."ADDRESSES" to "service_role";

grant truncate on table "public"."ADDRESSES" to "service_role";

grant update on table "public"."ADDRESSES" to "service_role";

grant delete on table "public"."ADDRESSES_MATERIALS" to "anon";

grant insert on table "public"."ADDRESSES_MATERIALS" to "anon";

grant references on table "public"."ADDRESSES_MATERIALS" to "anon";

grant select on table "public"."ADDRESSES_MATERIALS" to "anon";

grant trigger on table "public"."ADDRESSES_MATERIALS" to "anon";

grant truncate on table "public"."ADDRESSES_MATERIALS" to "anon";

grant update on table "public"."ADDRESSES_MATERIALS" to "anon";

grant delete on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant insert on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant references on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant select on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant trigger on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant truncate on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant update on table "public"."ADDRESSES_MATERIALS" to "authenticated";

grant delete on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant insert on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant references on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant select on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant trigger on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant truncate on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant update on table "public"."ADDRESSES_MATERIALS" to "service_role";

grant delete on table "public"."APPLICATIONS" to "anon";

grant insert on table "public"."APPLICATIONS" to "anon";

grant references on table "public"."APPLICATIONS" to "anon";

grant select on table "public"."APPLICATIONS" to "anon";

grant trigger on table "public"."APPLICATIONS" to "anon";

grant truncate on table "public"."APPLICATIONS" to "anon";

grant update on table "public"."APPLICATIONS" to "anon";

grant delete on table "public"."APPLICATIONS" to "authenticated";

grant insert on table "public"."APPLICATIONS" to "authenticated";

grant references on table "public"."APPLICATIONS" to "authenticated";

grant select on table "public"."APPLICATIONS" to "authenticated";

grant trigger on table "public"."APPLICATIONS" to "authenticated";

grant truncate on table "public"."APPLICATIONS" to "authenticated";

grant update on table "public"."APPLICATIONS" to "authenticated";

grant delete on table "public"."APPLICATIONS" to "service_role";

grant insert on table "public"."APPLICATIONS" to "service_role";

grant references on table "public"."APPLICATIONS" to "service_role";

grant select on table "public"."APPLICATIONS" to "service_role";

grant trigger on table "public"."APPLICATIONS" to "service_role";

grant truncate on table "public"."APPLICATIONS" to "service_role";

grant update on table "public"."APPLICATIONS" to "service_role";

grant delete on table "public"."CATEGORIES" to "anon";

grant insert on table "public"."CATEGORIES" to "anon";

grant references on table "public"."CATEGORIES" to "anon";

grant select on table "public"."CATEGORIES" to "anon";

grant trigger on table "public"."CATEGORIES" to "anon";

grant truncate on table "public"."CATEGORIES" to "anon";

grant update on table "public"."CATEGORIES" to "anon";

grant delete on table "public"."CATEGORIES" to "authenticated";

grant insert on table "public"."CATEGORIES" to "authenticated";

grant references on table "public"."CATEGORIES" to "authenticated";

grant select on table "public"."CATEGORIES" to "authenticated";

grant trigger on table "public"."CATEGORIES" to "authenticated";

grant truncate on table "public"."CATEGORIES" to "authenticated";

grant update on table "public"."CATEGORIES" to "authenticated";

grant delete on table "public"."CATEGORIES" to "service_role";

grant insert on table "public"."CATEGORIES" to "service_role";

grant references on table "public"."CATEGORIES" to "service_role";

grant select on table "public"."CATEGORIES" to "service_role";

grant trigger on table "public"."CATEGORIES" to "service_role";

grant truncate on table "public"."CATEGORIES" to "service_role";

grant update on table "public"."CATEGORIES" to "service_role";

grant delete on table "public"."COMMENTS" to "anon";

grant insert on table "public"."COMMENTS" to "anon";

grant references on table "public"."COMMENTS" to "anon";

grant select on table "public"."COMMENTS" to "anon";

grant trigger on table "public"."COMMENTS" to "anon";

grant truncate on table "public"."COMMENTS" to "anon";

grant update on table "public"."COMMENTS" to "anon";

grant delete on table "public"."COMMENTS" to "authenticated";

grant insert on table "public"."COMMENTS" to "authenticated";

grant references on table "public"."COMMENTS" to "authenticated";

grant select on table "public"."COMMENTS" to "authenticated";

grant trigger on table "public"."COMMENTS" to "authenticated";

grant truncate on table "public"."COMMENTS" to "authenticated";

grant update on table "public"."COMMENTS" to "authenticated";

grant delete on table "public"."COMMENTS" to "service_role";

grant insert on table "public"."COMMENTS" to "service_role";

grant references on table "public"."COMMENTS" to "service_role";

grant select on table "public"."COMMENTS" to "service_role";

grant trigger on table "public"."COMMENTS" to "service_role";

grant truncate on table "public"."COMMENTS" to "service_role";

grant update on table "public"."COMMENTS" to "service_role";

grant delete on table "public"."COMMENTS_REACTIONS" to "anon";

grant insert on table "public"."COMMENTS_REACTIONS" to "anon";

grant references on table "public"."COMMENTS_REACTIONS" to "anon";

grant select on table "public"."COMMENTS_REACTIONS" to "anon";

grant trigger on table "public"."COMMENTS_REACTIONS" to "anon";

grant truncate on table "public"."COMMENTS_REACTIONS" to "anon";

grant update on table "public"."COMMENTS_REACTIONS" to "anon";

grant delete on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant insert on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant references on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant select on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant trigger on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant truncate on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant update on table "public"."COMMENTS_REACTIONS" to "authenticated";

grant delete on table "public"."COMMENTS_REACTIONS" to "service_role";

grant insert on table "public"."COMMENTS_REACTIONS" to "service_role";

grant references on table "public"."COMMENTS_REACTIONS" to "service_role";

grant select on table "public"."COMMENTS_REACTIONS" to "service_role";

grant trigger on table "public"."COMMENTS_REACTIONS" to "service_role";

grant truncate on table "public"."COMMENTS_REACTIONS" to "service_role";

grant update on table "public"."COMMENTS_REACTIONS" to "service_role";

grant delete on table "public"."DONATIONS" to "anon";

grant insert on table "public"."DONATIONS" to "anon";

grant references on table "public"."DONATIONS" to "anon";

grant select on table "public"."DONATIONS" to "anon";

grant trigger on table "public"."DONATIONS" to "anon";

grant truncate on table "public"."DONATIONS" to "anon";

grant update on table "public"."DONATIONS" to "anon";

grant delete on table "public"."DONATIONS" to "authenticated";

grant insert on table "public"."DONATIONS" to "authenticated";

grant references on table "public"."DONATIONS" to "authenticated";

grant select on table "public"."DONATIONS" to "authenticated";

grant trigger on table "public"."DONATIONS" to "authenticated";

grant truncate on table "public"."DONATIONS" to "authenticated";

grant update on table "public"."DONATIONS" to "authenticated";

grant delete on table "public"."DONATIONS" to "service_role";

grant insert on table "public"."DONATIONS" to "service_role";

grant references on table "public"."DONATIONS" to "service_role";

grant select on table "public"."DONATIONS" to "service_role";

grant trigger on table "public"."DONATIONS" to "service_role";

grant truncate on table "public"."DONATIONS" to "service_role";

grant update on table "public"."DONATIONS" to "service_role";

grant delete on table "public"."EVENTS" to "anon";

grant insert on table "public"."EVENTS" to "anon";

grant references on table "public"."EVENTS" to "anon";

grant select on table "public"."EVENTS" to "anon";

grant trigger on table "public"."EVENTS" to "anon";

grant truncate on table "public"."EVENTS" to "anon";

grant update on table "public"."EVENTS" to "anon";

grant delete on table "public"."EVENTS" to "authenticated";

grant insert on table "public"."EVENTS" to "authenticated";

grant references on table "public"."EVENTS" to "authenticated";

grant select on table "public"."EVENTS" to "authenticated";

grant trigger on table "public"."EVENTS" to "authenticated";

grant truncate on table "public"."EVENTS" to "authenticated";

grant update on table "public"."EVENTS" to "authenticated";

grant delete on table "public"."EVENTS" to "service_role";

grant insert on table "public"."EVENTS" to "service_role";

grant references on table "public"."EVENTS" to "service_role";

grant select on table "public"."EVENTS" to "service_role";

grant trigger on table "public"."EVENTS" to "service_role";

grant truncate on table "public"."EVENTS" to "service_role";

grant update on table "public"."EVENTS" to "service_role";

grant delete on table "public"."LANDLORD" to "anon";

grant insert on table "public"."LANDLORD" to "anon";

grant references on table "public"."LANDLORD" to "anon";

grant select on table "public"."LANDLORD" to "anon";

grant trigger on table "public"."LANDLORD" to "anon";

grant truncate on table "public"."LANDLORD" to "anon";

grant update on table "public"."LANDLORD" to "anon";

grant delete on table "public"."LANDLORD" to "authenticated";

grant insert on table "public"."LANDLORD" to "authenticated";

grant references on table "public"."LANDLORD" to "authenticated";

grant select on table "public"."LANDLORD" to "authenticated";

grant trigger on table "public"."LANDLORD" to "authenticated";

grant truncate on table "public"."LANDLORD" to "authenticated";

grant update on table "public"."LANDLORD" to "authenticated";

grant delete on table "public"."LANDLORD" to "service_role";

grant insert on table "public"."LANDLORD" to "service_role";

grant references on table "public"."LANDLORD" to "service_role";

grant select on table "public"."LANDLORD" to "service_role";

grant trigger on table "public"."LANDLORD" to "service_role";

grant truncate on table "public"."LANDLORD" to "service_role";

grant update on table "public"."LANDLORD" to "service_role";

grant delete on table "public"."LEASE" to "anon";

grant insert on table "public"."LEASE" to "anon";

grant references on table "public"."LEASE" to "anon";

grant select on table "public"."LEASE" to "anon";

grant trigger on table "public"."LEASE" to "anon";

grant truncate on table "public"."LEASE" to "anon";

grant update on table "public"."LEASE" to "anon";

grant delete on table "public"."LEASE" to "authenticated";

grant insert on table "public"."LEASE" to "authenticated";

grant references on table "public"."LEASE" to "authenticated";

grant select on table "public"."LEASE" to "authenticated";

grant trigger on table "public"."LEASE" to "authenticated";

grant truncate on table "public"."LEASE" to "authenticated";

grant update on table "public"."LEASE" to "authenticated";

grant delete on table "public"."LEASE" to "service_role";

grant insert on table "public"."LEASE" to "service_role";

grant references on table "public"."LEASE" to "service_role";

grant select on table "public"."LEASE" to "service_role";

grant trigger on table "public"."LEASE" to "service_role";

grant truncate on table "public"."LEASE" to "service_role";

grant update on table "public"."LEASE" to "service_role";

grant delete on table "public"."MATCHES" to "anon";

grant insert on table "public"."MATCHES" to "anon";

grant references on table "public"."MATCHES" to "anon";

grant select on table "public"."MATCHES" to "anon";

grant trigger on table "public"."MATCHES" to "anon";

grant truncate on table "public"."MATCHES" to "anon";

grant update on table "public"."MATCHES" to "anon";

grant delete on table "public"."MATCHES" to "authenticated";

grant insert on table "public"."MATCHES" to "authenticated";

grant references on table "public"."MATCHES" to "authenticated";

grant select on table "public"."MATCHES" to "authenticated";

grant trigger on table "public"."MATCHES" to "authenticated";

grant truncate on table "public"."MATCHES" to "authenticated";

grant update on table "public"."MATCHES" to "authenticated";

grant delete on table "public"."MATCHES" to "service_role";

grant insert on table "public"."MATCHES" to "service_role";

grant references on table "public"."MATCHES" to "service_role";

grant select on table "public"."MATCHES" to "service_role";

grant trigger on table "public"."MATCHES" to "service_role";

grant truncate on table "public"."MATCHES" to "service_role";

grant update on table "public"."MATCHES" to "service_role";

grant delete on table "public"."MATERIALS" to "anon";

grant insert on table "public"."MATERIALS" to "anon";

grant references on table "public"."MATERIALS" to "anon";

grant select on table "public"."MATERIALS" to "anon";

grant trigger on table "public"."MATERIALS" to "anon";

grant truncate on table "public"."MATERIALS" to "anon";

grant update on table "public"."MATERIALS" to "anon";

grant delete on table "public"."MATERIALS" to "authenticated";

grant insert on table "public"."MATERIALS" to "authenticated";

grant references on table "public"."MATERIALS" to "authenticated";

grant select on table "public"."MATERIALS" to "authenticated";

grant trigger on table "public"."MATERIALS" to "authenticated";

grant truncate on table "public"."MATERIALS" to "authenticated";

grant update on table "public"."MATERIALS" to "authenticated";

grant delete on table "public"."MATERIALS" to "service_role";

grant insert on table "public"."MATERIALS" to "service_role";

grant references on table "public"."MATERIALS" to "service_role";

grant select on table "public"."MATERIALS" to "service_role";

grant trigger on table "public"."MATERIALS" to "service_role";

grant truncate on table "public"."MATERIALS" to "service_role";

grant update on table "public"."MATERIALS" to "service_role";

grant delete on table "public"."MESSAGES" to "anon";

grant insert on table "public"."MESSAGES" to "anon";

grant references on table "public"."MESSAGES" to "anon";

grant select on table "public"."MESSAGES" to "anon";

grant trigger on table "public"."MESSAGES" to "anon";

grant truncate on table "public"."MESSAGES" to "anon";

grant update on table "public"."MESSAGES" to "anon";

grant delete on table "public"."MESSAGES" to "authenticated";

grant insert on table "public"."MESSAGES" to "authenticated";

grant references on table "public"."MESSAGES" to "authenticated";

grant select on table "public"."MESSAGES" to "authenticated";

grant trigger on table "public"."MESSAGES" to "authenticated";

grant truncate on table "public"."MESSAGES" to "authenticated";

grant update on table "public"."MESSAGES" to "authenticated";

grant delete on table "public"."MESSAGES" to "service_role";

grant insert on table "public"."MESSAGES" to "service_role";

grant references on table "public"."MESSAGES" to "service_role";

grant select on table "public"."MESSAGES" to "service_role";

grant trigger on table "public"."MESSAGES" to "service_role";

grant truncate on table "public"."MESSAGES" to "service_role";

grant update on table "public"."MESSAGES" to "service_role";

grant delete on table "public"."NEWS" to "anon";

grant insert on table "public"."NEWS" to "anon";

grant references on table "public"."NEWS" to "anon";

grant select on table "public"."NEWS" to "anon";

grant trigger on table "public"."NEWS" to "anon";

grant truncate on table "public"."NEWS" to "anon";

grant update on table "public"."NEWS" to "anon";

grant delete on table "public"."NEWS" to "authenticated";

grant insert on table "public"."NEWS" to "authenticated";

grant references on table "public"."NEWS" to "authenticated";

grant select on table "public"."NEWS" to "authenticated";

grant trigger on table "public"."NEWS" to "authenticated";

grant truncate on table "public"."NEWS" to "authenticated";

grant update on table "public"."NEWS" to "authenticated";

grant delete on table "public"."NEWS" to "service_role";

grant insert on table "public"."NEWS" to "service_role";

grant references on table "public"."NEWS" to "service_role";

grant select on table "public"."NEWS" to "service_role";

grant trigger on table "public"."NEWS" to "service_role";

grant truncate on table "public"."NEWS" to "service_role";

grant update on table "public"."NEWS" to "service_role";

grant delete on table "public"."POLLS" to "anon";

grant insert on table "public"."POLLS" to "anon";

grant references on table "public"."POLLS" to "anon";

grant select on table "public"."POLLS" to "anon";

grant trigger on table "public"."POLLS" to "anon";

grant truncate on table "public"."POLLS" to "anon";

grant update on table "public"."POLLS" to "anon";

grant delete on table "public"."POLLS" to "authenticated";

grant insert on table "public"."POLLS" to "authenticated";

grant references on table "public"."POLLS" to "authenticated";

grant select on table "public"."POLLS" to "authenticated";

grant trigger on table "public"."POLLS" to "authenticated";

grant truncate on table "public"."POLLS" to "authenticated";

grant update on table "public"."POLLS" to "authenticated";

grant delete on table "public"."POLLS" to "service_role";

grant insert on table "public"."POLLS" to "service_role";

grant references on table "public"."POLLS" to "service_role";

grant select on table "public"."POLLS" to "service_role";

grant trigger on table "public"."POLLS" to "service_role";

grant truncate on table "public"."POLLS" to "service_role";

grant update on table "public"."POLLS" to "service_role";

grant delete on table "public"."POLLS_ANSWERS" to "anon";

grant insert on table "public"."POLLS_ANSWERS" to "anon";

grant references on table "public"."POLLS_ANSWERS" to "anon";

grant select on table "public"."POLLS_ANSWERS" to "anon";

grant trigger on table "public"."POLLS_ANSWERS" to "anon";

grant truncate on table "public"."POLLS_ANSWERS" to "anon";

grant update on table "public"."POLLS_ANSWERS" to "anon";

grant delete on table "public"."POLLS_ANSWERS" to "authenticated";

grant insert on table "public"."POLLS_ANSWERS" to "authenticated";

grant references on table "public"."POLLS_ANSWERS" to "authenticated";

grant select on table "public"."POLLS_ANSWERS" to "authenticated";

grant trigger on table "public"."POLLS_ANSWERS" to "authenticated";

grant truncate on table "public"."POLLS_ANSWERS" to "authenticated";

grant update on table "public"."POLLS_ANSWERS" to "authenticated";

grant delete on table "public"."POLLS_ANSWERS" to "service_role";

grant insert on table "public"."POLLS_ANSWERS" to "service_role";

grant references on table "public"."POLLS_ANSWERS" to "service_role";

grant select on table "public"."POLLS_ANSWERS" to "service_role";

grant trigger on table "public"."POLLS_ANSWERS" to "service_role";

grant truncate on table "public"."POLLS_ANSWERS" to "service_role";

grant update on table "public"."POLLS_ANSWERS" to "service_role";

grant delete on table "public"."POSTS" to "anon";

grant insert on table "public"."POSTS" to "anon";

grant references on table "public"."POSTS" to "anon";

grant select on table "public"."POSTS" to "anon";

grant trigger on table "public"."POSTS" to "anon";

grant truncate on table "public"."POSTS" to "anon";

grant update on table "public"."POSTS" to "anon";

grant delete on table "public"."POSTS" to "authenticated";

grant insert on table "public"."POSTS" to "authenticated";

grant references on table "public"."POSTS" to "authenticated";

grant select on table "public"."POSTS" to "authenticated";

grant trigger on table "public"."POSTS" to "authenticated";

grant truncate on table "public"."POSTS" to "authenticated";

grant update on table "public"."POSTS" to "authenticated";

grant delete on table "public"."POSTS" to "service_role";

grant insert on table "public"."POSTS" to "service_role";

grant references on table "public"."POSTS" to "service_role";

grant select on table "public"."POSTS" to "service_role";

grant trigger on table "public"."POSTS" to "service_role";

grant truncate on table "public"."POSTS" to "service_role";

grant update on table "public"."POSTS" to "service_role";

grant delete on table "public"."POSTS_REACTIONS" to "anon";

grant insert on table "public"."POSTS_REACTIONS" to "anon";

grant references on table "public"."POSTS_REACTIONS" to "anon";

grant select on table "public"."POSTS_REACTIONS" to "anon";

grant trigger on table "public"."POSTS_REACTIONS" to "anon";

grant truncate on table "public"."POSTS_REACTIONS" to "anon";

grant update on table "public"."POSTS_REACTIONS" to "anon";

grant delete on table "public"."POSTS_REACTIONS" to "authenticated";

grant insert on table "public"."POSTS_REACTIONS" to "authenticated";

grant references on table "public"."POSTS_REACTIONS" to "authenticated";

grant select on table "public"."POSTS_REACTIONS" to "authenticated";

grant trigger on table "public"."POSTS_REACTIONS" to "authenticated";

grant truncate on table "public"."POSTS_REACTIONS" to "authenticated";

grant update on table "public"."POSTS_REACTIONS" to "authenticated";

grant delete on table "public"."POSTS_REACTIONS" to "service_role";

grant insert on table "public"."POSTS_REACTIONS" to "service_role";

grant references on table "public"."POSTS_REACTIONS" to "service_role";

grant select on table "public"."POSTS_REACTIONS" to "service_role";

grant trigger on table "public"."POSTS_REACTIONS" to "service_role";

grant truncate on table "public"."POSTS_REACTIONS" to "service_role";

grant update on table "public"."POSTS_REACTIONS" to "service_role";

grant delete on table "public"."PRODUCTS" to "anon";

grant insert on table "public"."PRODUCTS" to "anon";

grant references on table "public"."PRODUCTS" to "anon";

grant select on table "public"."PRODUCTS" to "anon";

grant trigger on table "public"."PRODUCTS" to "anon";

grant truncate on table "public"."PRODUCTS" to "anon";

grant update on table "public"."PRODUCTS" to "anon";

grant delete on table "public"."PRODUCTS" to "authenticated";

grant insert on table "public"."PRODUCTS" to "authenticated";

grant references on table "public"."PRODUCTS" to "authenticated";

grant select on table "public"."PRODUCTS" to "authenticated";

grant trigger on table "public"."PRODUCTS" to "authenticated";

grant truncate on table "public"."PRODUCTS" to "authenticated";

grant update on table "public"."PRODUCTS" to "authenticated";

grant delete on table "public"."PRODUCTS" to "service_role";

grant insert on table "public"."PRODUCTS" to "service_role";

grant references on table "public"."PRODUCTS" to "service_role";

grant select on table "public"."PRODUCTS" to "service_role";

grant trigger on table "public"."PRODUCTS" to "service_role";

grant truncate on table "public"."PRODUCTS" to "service_role";

grant update on table "public"."PRODUCTS" to "service_role";

grant delete on table "public"."PROPOSALS" to "anon";

grant insert on table "public"."PROPOSALS" to "anon";

grant references on table "public"."PROPOSALS" to "anon";

grant select on table "public"."PROPOSALS" to "anon";

grant trigger on table "public"."PROPOSALS" to "anon";

grant truncate on table "public"."PROPOSALS" to "anon";

grant update on table "public"."PROPOSALS" to "anon";

grant delete on table "public"."PROPOSALS" to "authenticated";

grant insert on table "public"."PROPOSALS" to "authenticated";

grant references on table "public"."PROPOSALS" to "authenticated";

grant select on table "public"."PROPOSALS" to "authenticated";

grant trigger on table "public"."PROPOSALS" to "authenticated";

grant truncate on table "public"."PROPOSALS" to "authenticated";

grant update on table "public"."PROPOSALS" to "authenticated";

grant delete on table "public"."PROPOSALS" to "service_role";

grant insert on table "public"."PROPOSALS" to "service_role";

grant references on table "public"."PROPOSALS" to "service_role";

grant select on table "public"."PROPOSALS" to "service_role";

grant trigger on table "public"."PROPOSALS" to "service_role";

grant truncate on table "public"."PROPOSALS" to "service_role";

grant update on table "public"."PROPOSALS" to "service_role";

grant delete on table "public"."RESERVED" to "anon";

grant insert on table "public"."RESERVED" to "anon";

grant references on table "public"."RESERVED" to "anon";

grant select on table "public"."RESERVED" to "anon";

grant trigger on table "public"."RESERVED" to "anon";

grant truncate on table "public"."RESERVED" to "anon";

grant update on table "public"."RESERVED" to "anon";

grant delete on table "public"."RESERVED" to "authenticated";

grant insert on table "public"."RESERVED" to "authenticated";

grant references on table "public"."RESERVED" to "authenticated";

grant select on table "public"."RESERVED" to "authenticated";

grant trigger on table "public"."RESERVED" to "authenticated";

grant truncate on table "public"."RESERVED" to "authenticated";

grant update on table "public"."RESERVED" to "authenticated";

grant delete on table "public"."RESERVED" to "service_role";

grant insert on table "public"."RESERVED" to "service_role";

grant references on table "public"."RESERVED" to "service_role";

grant select on table "public"."RESERVED" to "service_role";

grant trigger on table "public"."RESERVED" to "service_role";

grant truncate on table "public"."RESERVED" to "service_role";

grant update on table "public"."RESERVED" to "service_role";

grant delete on table "public"."ROLES" to "anon";

grant insert on table "public"."ROLES" to "anon";

grant references on table "public"."ROLES" to "anon";

grant select on table "public"."ROLES" to "anon";

grant trigger on table "public"."ROLES" to "anon";

grant truncate on table "public"."ROLES" to "anon";

grant update on table "public"."ROLES" to "anon";

grant delete on table "public"."ROLES" to "authenticated";

grant insert on table "public"."ROLES" to "authenticated";

grant references on table "public"."ROLES" to "authenticated";

grant select on table "public"."ROLES" to "authenticated";

grant trigger on table "public"."ROLES" to "authenticated";

grant truncate on table "public"."ROLES" to "authenticated";

grant update on table "public"."ROLES" to "authenticated";

grant delete on table "public"."ROLES" to "service_role";

grant insert on table "public"."ROLES" to "service_role";

grant references on table "public"."ROLES" to "service_role";

grant select on table "public"."ROLES" to "service_role";

grant trigger on table "public"."ROLES" to "service_role";

grant truncate on table "public"."ROLES" to "service_role";

grant update on table "public"."ROLES" to "service_role";

grant delete on table "public"."SPORTS" to "anon";

grant insert on table "public"."SPORTS" to "anon";

grant references on table "public"."SPORTS" to "anon";

grant select on table "public"."SPORTS" to "anon";

grant trigger on table "public"."SPORTS" to "anon";

grant truncate on table "public"."SPORTS" to "anon";

grant update on table "public"."SPORTS" to "anon";

grant delete on table "public"."SPORTS" to "authenticated";

grant insert on table "public"."SPORTS" to "authenticated";

grant references on table "public"."SPORTS" to "authenticated";

grant select on table "public"."SPORTS" to "authenticated";

grant trigger on table "public"."SPORTS" to "authenticated";

grant truncate on table "public"."SPORTS" to "authenticated";

grant update on table "public"."SPORTS" to "authenticated";

grant delete on table "public"."SPORTS" to "service_role";

grant insert on table "public"."SPORTS" to "service_role";

grant references on table "public"."SPORTS" to "service_role";

grant select on table "public"."SPORTS" to "service_role";

grant trigger on table "public"."SPORTS" to "service_role";

grant truncate on table "public"."SPORTS" to "service_role";

grant update on table "public"."SPORTS" to "service_role";

grant delete on table "public"."TEAMS" to "anon";

grant insert on table "public"."TEAMS" to "anon";

grant references on table "public"."TEAMS" to "anon";

grant select on table "public"."TEAMS" to "anon";

grant trigger on table "public"."TEAMS" to "anon";

grant truncate on table "public"."TEAMS" to "anon";

grant update on table "public"."TEAMS" to "anon";

grant delete on table "public"."TEAMS" to "authenticated";

grant insert on table "public"."TEAMS" to "authenticated";

grant references on table "public"."TEAMS" to "authenticated";

grant select on table "public"."TEAMS" to "authenticated";

grant trigger on table "public"."TEAMS" to "authenticated";

grant truncate on table "public"."TEAMS" to "authenticated";

grant update on table "public"."TEAMS" to "authenticated";

grant delete on table "public"."TEAMS" to "service_role";

grant insert on table "public"."TEAMS" to "service_role";

grant references on table "public"."TEAMS" to "service_role";

grant select on table "public"."TEAMS" to "service_role";

grant trigger on table "public"."TEAMS" to "service_role";

grant truncate on table "public"."TEAMS" to "service_role";

grant update on table "public"."TEAMS" to "service_role";

grant delete on table "public"."TEAMS_MATCHES" to "anon";

grant insert on table "public"."TEAMS_MATCHES" to "anon";

grant references on table "public"."TEAMS_MATCHES" to "anon";

grant select on table "public"."TEAMS_MATCHES" to "anon";

grant trigger on table "public"."TEAMS_MATCHES" to "anon";

grant truncate on table "public"."TEAMS_MATCHES" to "anon";

grant update on table "public"."TEAMS_MATCHES" to "anon";

grant delete on table "public"."TEAMS_MATCHES" to "authenticated";

grant insert on table "public"."TEAMS_MATCHES" to "authenticated";

grant references on table "public"."TEAMS_MATCHES" to "authenticated";

grant select on table "public"."TEAMS_MATCHES" to "authenticated";

grant trigger on table "public"."TEAMS_MATCHES" to "authenticated";

grant truncate on table "public"."TEAMS_MATCHES" to "authenticated";

grant update on table "public"."TEAMS_MATCHES" to "authenticated";

grant delete on table "public"."TEAMS_MATCHES" to "service_role";

grant insert on table "public"."TEAMS_MATCHES" to "service_role";

grant references on table "public"."TEAMS_MATCHES" to "service_role";

grant select on table "public"."TEAMS_MATCHES" to "service_role";

grant trigger on table "public"."TEAMS_MATCHES" to "service_role";

grant truncate on table "public"."TEAMS_MATCHES" to "service_role";

grant update on table "public"."TEAMS_MATCHES" to "service_role";

grant delete on table "public"."TOURNAMENTS" to "anon";

grant insert on table "public"."TOURNAMENTS" to "anon";

grant references on table "public"."TOURNAMENTS" to "anon";

grant select on table "public"."TOURNAMENTS" to "anon";

grant trigger on table "public"."TOURNAMENTS" to "anon";

grant truncate on table "public"."TOURNAMENTS" to "anon";

grant update on table "public"."TOURNAMENTS" to "anon";

grant delete on table "public"."TOURNAMENTS" to "authenticated";

grant insert on table "public"."TOURNAMENTS" to "authenticated";

grant references on table "public"."TOURNAMENTS" to "authenticated";

grant select on table "public"."TOURNAMENTS" to "authenticated";

grant trigger on table "public"."TOURNAMENTS" to "authenticated";

grant truncate on table "public"."TOURNAMENTS" to "authenticated";

grant update on table "public"."TOURNAMENTS" to "authenticated";

grant delete on table "public"."TOURNAMENTS" to "service_role";

grant insert on table "public"."TOURNAMENTS" to "service_role";

grant references on table "public"."TOURNAMENTS" to "service_role";

grant select on table "public"."TOURNAMENTS" to "service_role";

grant trigger on table "public"."TOURNAMENTS" to "service_role";

grant truncate on table "public"."TOURNAMENTS" to "service_role";

grant update on table "public"."TOURNAMENTS" to "service_role";

grant delete on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant insert on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant references on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant select on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant trigger on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant truncate on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant update on table "public"."TOURNAMENTS_MATCHES" to "anon";

grant delete on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant insert on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant references on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant select on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant trigger on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant truncate on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant update on table "public"."TOURNAMENTS_MATCHES" to "authenticated";

grant delete on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant insert on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant references on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant select on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant trigger on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant truncate on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant update on table "public"."TOURNAMENTS_MATCHES" to "service_role";

grant delete on table "public"."USERS" to "anon";

grant insert on table "public"."USERS" to "anon";

grant references on table "public"."USERS" to "anon";

grant select on table "public"."USERS" to "anon";

grant trigger on table "public"."USERS" to "anon";

grant truncate on table "public"."USERS" to "anon";

grant update on table "public"."USERS" to "anon";

grant delete on table "public"."USERS" to "authenticated";

grant insert on table "public"."USERS" to "authenticated";

grant references on table "public"."USERS" to "authenticated";

grant select on table "public"."USERS" to "authenticated";

grant trigger on table "public"."USERS" to "authenticated";

grant truncate on table "public"."USERS" to "authenticated";

grant update on table "public"."USERS" to "authenticated";

grant delete on table "public"."USERS" to "service_role";

grant insert on table "public"."USERS" to "service_role";

grant references on table "public"."USERS" to "service_role";

grant select on table "public"."USERS" to "service_role";

grant trigger on table "public"."USERS" to "service_role";

grant truncate on table "public"."USERS" to "service_role";

grant update on table "public"."USERS" to "service_role";

grant delete on table "public"."USERS_ROLES" to "anon";

grant insert on table "public"."USERS_ROLES" to "anon";

grant references on table "public"."USERS_ROLES" to "anon";

grant select on table "public"."USERS_ROLES" to "anon";

grant trigger on table "public"."USERS_ROLES" to "anon";

grant truncate on table "public"."USERS_ROLES" to "anon";

grant update on table "public"."USERS_ROLES" to "anon";

grant delete on table "public"."USERS_ROLES" to "authenticated";

grant insert on table "public"."USERS_ROLES" to "authenticated";

grant references on table "public"."USERS_ROLES" to "authenticated";

grant select on table "public"."USERS_ROLES" to "authenticated";

grant trigger on table "public"."USERS_ROLES" to "authenticated";

grant truncate on table "public"."USERS_ROLES" to "authenticated";

grant update on table "public"."USERS_ROLES" to "authenticated";

grant delete on table "public"."USERS_ROLES" to "service_role";

grant insert on table "public"."USERS_ROLES" to "service_role";

grant references on table "public"."USERS_ROLES" to "service_role";

grant select on table "public"."USERS_ROLES" to "service_role";

grant trigger on table "public"."USERS_ROLES" to "service_role";

grant truncate on table "public"."USERS_ROLES" to "service_role";

grant update on table "public"."USERS_ROLES" to "service_role";

grant delete on table "public"."USERS_TEAMS" to "anon";

grant insert on table "public"."USERS_TEAMS" to "anon";

grant references on table "public"."USERS_TEAMS" to "anon";

grant select on table "public"."USERS_TEAMS" to "anon";

grant trigger on table "public"."USERS_TEAMS" to "anon";

grant truncate on table "public"."USERS_TEAMS" to "anon";

grant update on table "public"."USERS_TEAMS" to "anon";

grant delete on table "public"."USERS_TEAMS" to "authenticated";

grant insert on table "public"."USERS_TEAMS" to "authenticated";

grant references on table "public"."USERS_TEAMS" to "authenticated";

grant select on table "public"."USERS_TEAMS" to "authenticated";

grant trigger on table "public"."USERS_TEAMS" to "authenticated";

grant truncate on table "public"."USERS_TEAMS" to "authenticated";

grant update on table "public"."USERS_TEAMS" to "authenticated";

grant delete on table "public"."USERS_TEAMS" to "service_role";

grant insert on table "public"."USERS_TEAMS" to "service_role";

grant references on table "public"."USERS_TEAMS" to "service_role";

grant select on table "public"."USERS_TEAMS" to "service_role";

grant trigger on table "public"."USERS_TEAMS" to "service_role";

grant truncate on table "public"."USERS_TEAMS" to "service_role";

grant update on table "public"."USERS_TEAMS" to "service_role";


INSERT INTO "public"."ROLES" (id, name)
VALUES (1, 'BANNED'),
       (2, 'MEMBER'),
       (3, 'REDACTOR'),
       (4, 'MODERATOR'),
       (5, 'ADMIN'),
       (6, 'DIRECTOR'),
       (7, 'SECRATARY'),
       (8, 'TREASURER'),
       (9, 'PRESIDENT')