create type "public"."reaction" as enum ('like');

create table "public"."POSTS_CATEGORIES" (
    "id" bigint generated by default as identity not null,
    "id_post" integer not null,
    "id_category" bigint not null
);


create table "public"."POSTS_VIEWS" (
    "id_user" integer generated by default as identity not null,
    "viewed" timestamp with time zone not null default now(),
    "id_post" integer not null
);


alter table "public"."POSTS" add column "description" text;

alter table "public"."POSTS_REACTIONS" drop column "like";

alter table "public"."POSTS_REACTIONS" alter column "reaction" set default 'like'::reaction;

alter table "public"."POSTS_REACTIONS" alter column "reaction" set data type reaction using "reaction"::reaction;

CREATE UNIQUE INDEX "POSTS_CATEGORIES_pkey" ON public."POSTS_CATEGORIES" USING btree (id);

CREATE UNIQUE INDEX "POSTS_VIEWS_pkey" ON public."POSTS_VIEWS" USING btree (id_user, id_post);

alter table "public"."POSTS_CATEGORIES" add constraint "POSTS_CATEGORIES_pkey" PRIMARY KEY using index "POSTS_CATEGORIES_pkey";

alter table "public"."POSTS_VIEWS" add constraint "POSTS_VIEWS_pkey" PRIMARY KEY using index "POSTS_VIEWS_pkey";

alter table "public"."POSTS_CATEGORIES" add constraint "POSTS_CATEGORIES_id_category_fkey" FOREIGN KEY (id_category) REFERENCES "CATEGORIES"(id) not valid;

alter table "public"."POSTS_CATEGORIES" validate constraint "POSTS_CATEGORIES_id_category_fkey";

alter table "public"."POSTS_CATEGORIES" add constraint "POSTS_CATEGORIES_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."POSTS_CATEGORIES" validate constraint "POSTS_CATEGORIES_id_post_fkey";

alter table "public"."POSTS_VIEWS" add constraint "POSTS_VIEWS_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) not valid;

alter table "public"."POSTS_VIEWS" validate constraint "POSTS_VIEWS_id_post_fkey";

alter table "public"."POSTS_VIEWS" add constraint "POSTS_VIEWS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) not valid;

alter table "public"."POSTS_VIEWS" validate constraint "POSTS_VIEWS_id_user_fkey";

grant delete on table "public"."POSTS_CATEGORIES" to "anon";

grant insert on table "public"."POSTS_CATEGORIES" to "anon";

grant references on table "public"."POSTS_CATEGORIES" to "anon";

grant select on table "public"."POSTS_CATEGORIES" to "anon";

grant trigger on table "public"."POSTS_CATEGORIES" to "anon";

grant truncate on table "public"."POSTS_CATEGORIES" to "anon";

grant update on table "public"."POSTS_CATEGORIES" to "anon";

grant delete on table "public"."POSTS_CATEGORIES" to "authenticated";

grant insert on table "public"."POSTS_CATEGORIES" to "authenticated";

grant references on table "public"."POSTS_CATEGORIES" to "authenticated";

grant select on table "public"."POSTS_CATEGORIES" to "authenticated";

grant trigger on table "public"."POSTS_CATEGORIES" to "authenticated";

grant truncate on table "public"."POSTS_CATEGORIES" to "authenticated";

grant update on table "public"."POSTS_CATEGORIES" to "authenticated";

grant delete on table "public"."POSTS_CATEGORIES" to "service_role";

grant insert on table "public"."POSTS_CATEGORIES" to "service_role";

grant references on table "public"."POSTS_CATEGORIES" to "service_role";

grant select on table "public"."POSTS_CATEGORIES" to "service_role";

grant trigger on table "public"."POSTS_CATEGORIES" to "service_role";

grant truncate on table "public"."POSTS_CATEGORIES" to "service_role";

grant update on table "public"."POSTS_CATEGORIES" to "service_role";

grant delete on table "public"."POSTS_VIEWS" to "anon";

grant insert on table "public"."POSTS_VIEWS" to "anon";

grant references on table "public"."POSTS_VIEWS" to "anon";

grant select on table "public"."POSTS_VIEWS" to "anon";

grant trigger on table "public"."POSTS_VIEWS" to "anon";

grant truncate on table "public"."POSTS_VIEWS" to "anon";

grant update on table "public"."POSTS_VIEWS" to "anon";

grant delete on table "public"."POSTS_VIEWS" to "authenticated";

grant insert on table "public"."POSTS_VIEWS" to "authenticated";

grant references on table "public"."POSTS_VIEWS" to "authenticated";

grant select on table "public"."POSTS_VIEWS" to "authenticated";

grant trigger on table "public"."POSTS_VIEWS" to "authenticated";

grant truncate on table "public"."POSTS_VIEWS" to "authenticated";

grant update on table "public"."POSTS_VIEWS" to "authenticated";

grant delete on table "public"."POSTS_VIEWS" to "service_role";

grant insert on table "public"."POSTS_VIEWS" to "service_role";

grant references on table "public"."POSTS_VIEWS" to "service_role";

grant select on table "public"."POSTS_VIEWS" to "service_role";

grant trigger on table "public"."POSTS_VIEWS" to "service_role";

grant truncate on table "public"."POSTS_VIEWS" to "service_role";

grant update on table "public"."POSTS_VIEWS" to "service_role";

alter table "public"."COMMENTS" drop constraint "public_COMMENTS_id_post_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_post_fkey" FOREIGN KEY (id_post) REFERENCES "POSTS"(id) ON DELETE SET NULL not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_post_fkey";

alter table "public"."COMMENTS" drop constraint "comments_id_comment_fkey";

alter table "public"."COMMENTS" drop constraint "public_COMMENTS_id_activity_fkey";

alter table "public"."COMMENTS" drop constraint "public_COMMENTS_id_user_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_response_fkey" FOREIGN KEY (id_response) REFERENCES "COMMENTS"(id) ON DELETE CASCADE not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_response_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_activity_fkey" FOREIGN KEY (id_activity) REFERENCES "ACTIVITIES"(id) ON DELETE SET NULL not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_activity_fkey";

alter table "public"."COMMENTS" add constraint "public_COMMENTS_id_user_fkey" FOREIGN KEY (id_user) REFERENCES "USERS"(id) ON DELETE CASCADE not valid;

alter table "public"."COMMENTS" validate constraint "public_COMMENTS_id_user_fkey";
