create table "public"."ASSEMBLIES" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "date" timestamp with time zone not null,
    "location" bigint,
    "lawsuit" text
);


create table "public"."ASSEMBLIES_ATTENDEES" (
    "id" bigint generated by default as identity not null,
    "id_assembly" bigint,
    "id_member" integer
);

CREATE UNIQUE INDEX "ASSEMBLIES_ATTENDEES_pkey" ON public."ASSEMBLIES_ATTENDEES" USING btree (id);

CREATE UNIQUE INDEX "ASSEMBLIES_pkey" ON public."ASSEMBLIES" USING btree (id);

alter table "public"."ASSEMBLIES" add constraint "ASSEMBLIES_pkey" PRIMARY KEY using index "ASSEMBLIES_pkey";

alter table "public"."ASSEMBLIES" add constraint "ASSEMBLIES_location_fkey" FOREIGN KEY (location) REFERENCES "ADDRESSES"(id) not valid;

alter table "public"."ASSEMBLIES" validate constraint "ASSEMBLIES_location_fkey";

alter table "public"."ASSEMBLIES_ATTENDEES" add constraint "ASSEMBLIES_ATTENDEES_pkey" PRIMARY KEY using index "ASSEMBLIES_ATTENDEES_pkey";

alter table "public"."ASSEMBLIES_ATTENDEES" add constraint "ASSEMBLIES_ATTENDEES_id_assembly_fkey" FOREIGN KEY (id_assembly) REFERENCES "ASSEMBLIES"(id) not valid;

alter table "public"."ASSEMBLIES_ATTENDEES" validate constraint "ASSEMBLIES_ATTENDEES_id_assembly_fkey";

alter table "public"."ASSEMBLIES_ATTENDEES" add constraint "ASSEMBLIES_ATTENDEES_id_member_fkey" FOREIGN KEY (id_member) REFERENCES "USERS"(id) not valid;

alter table "public"."ASSEMBLIES_ATTENDEES" validate constraint "ASSEMBLIES_ATTENDEES_id_member_fkey";

alter table "public"."POLLS" add column "assembly" bigint;
